import type { MissionTemplate } from '../missions.js';

/** The district band, D- to C+: work against the Combine's offices, depots, checkpoints and patrols. */
export const DISTRICT_JOBS: readonly MissionTemplate[] = [
  {
    id: 'permit-office-fire',
    name: 'Permit Office Fire',
    brief:
      'The permit office keeps paper copies of every eviction order. Tonight it keeps fewer. Be gone before the sprinklers remember they work.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'further',
    durationMinutes: 45,
    spoils: { caps: 40, supplies: 20 },
    leanings: ['breach', 'stealth'],
  },
  {
    id: 'ration-card-press',
    name: 'Ration Card Press',
    brief:
      'A Combine print shop runs ration cards on a press older than the district. Nobody counts the blanks. Take a crate and someone who can match the ink.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 40,
    spoils: { caps: 30, supplies: 40 },
    leanings: ['con', 'plan'],
  },
  {
    id: 'clinic-cold-store',
    name: 'Clinic Cold Store',
    brief:
      "The ward clinic's fridge holds insulin nobody on the lower tiers is cleared for. The lock is cheap. The duty nurse looks away for a price.",
    kind: 'standard',
    grades: ['D-', 'C-'],
    travelBand: 'further',
    durationMinutes: 50,
    spoils: { supplies: 60, caps: 10 },
    leanings: ['medic', 'stealth', 'talk'],
  },
  {
    id: 'tram-depot-strip',
    name: 'Tram Depot Strip',
    brief:
      'Three trams sit in the Combine depot waiting for parts that will never come. Help them wait lighter. Copper first, seats if there is time.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { scrap: 50, highQualityMetal: 10 },
    leanings: ['salvage', 'haul'],
  },
  {
    id: 'notice-board-swap',
    name: 'Notice Board Swap',
    brief:
      "The housing office posts eviction lists on Tuesdays. Swap tonight's list for a blank one and forty families get another week.",
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { caps: 30, supplies: 30 },
    leanings: ['con', 'stealth'],
  },
  {
    id: 'canal-lock-haul',
    name: 'Canal Lock Haul',
    brief:
      'A Combine barge is stuck at the lower lock with its pumps dead. Fix the pump and keep whatever falls off the deck while you work.',
    kind: 'standard',
    grades: ['D-', 'C-'],
    travelBand: 'further',
    durationMinutes: 70,
    spoils: { oil: 30, planks: 30, scrap: 20 },
    leanings: ['repair', 'haul'],
  },
  {
    id: 'court-basement',
    name: 'Court Basement',
    brief:
      'The district court stores seized goods in its basement and seizes more than it logs. Read the ledger first, then take what is not in it.',
    kind: 'standard',
    grades: ['D', 'C'],
    travelBand: 'further',
    durationMinutes: 80,
    spoils: { caps: 40, supplies: 20, scrap: 20 },
    leanings: ['intel', 'stealth', 'haul'],
  },
  {
    id: 'rooftop-antenna',
    name: 'Rooftop Antenna',
    brief:
      'The Combine repeater on Block Nine tells every patrol where to stand. Climb up, turn it a few degrees, and let them stand somewhere else.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 45,
    spoils: { scrap: 30, caps: 20 },
    leanings: ['climb', 'wire'],
  },
  {
    id: 'depot-recount',
    name: 'Depot Recount',
    brief:
      'A supply depot is due an audit next week. The quartermaster pays well to have the count come out even, and asks nothing about how.',
    kind: 'standard',
    grades: ['D', 'C-'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { caps: 50, supplies: 20 },
    leanings: ['intel', 'plan', 'con'],
  },
  {
    id: 'turnstile-skim',
    name: 'Turnstile Skim',
    brief:
      'The transit hub turnstiles keep coins in a box nobody has emptied since fares went digital. Bring a wrench and a crowd to stand in front.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { caps: 60 },
    leanings: ['repair', 'stealth'],
  },
  {
    id: 'block-boiler',
    name: 'Block Boiler',
    brief:
      'Tower Fourteen has had no hot water since spring because the Combine will not send a fitter. Send yours. The tenants pay in what they have.',
    kind: 'standard',
    grades: ['D-', 'C-'],
    travelBand: 'close',
    durationMinutes: 90,
    spoils: { supplies: 40, planks: 20, caps: 10 },
    leanings: ['repair', 'parley'],
  },
  {
    id: 'implant-repossession',
    name: 'Implant Repossession',
    brief:
      'A back alley implant clinic owes the Combine for parts. The Combine sold the debt to you. Collect it in parts.',
    kind: 'standard',
    grades: ['D', 'C-'],
    travelBand: 'further',
    durationMinutes: 60,
    spoils: { highQualityMetal: 15, scrap: 30, caps: 20 },
    leanings: ['muscle', 'chrome'],
  },
  {
    id: 'patrol-rota',
    name: 'Patrol Rota',
    brief:
      "A Combine sergeant leaves the week's patrol rota in his locker, and his locker key in a bar. Photograph it, put it back, buy him a drink.",
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 35,
    spoils: { caps: 30, supplies: 20 },
    leanings: ['intel', 'stealth', 'talk'],
  },
  {
    id: 'valve-house-bypass',
    name: 'Valve House Bypass',
    brief:
      'The Combine rations water block by block through one valve house. Give the east blocks a pipe the meters do not know about.',
    kind: 'standard',
    grades: ['D', 'C'],
    travelBand: 'further',
    durationMinutes: 100,
    spoils: { supplies: 40, scrap: 20, oil: 10 },
    leanings: ['repair', 'plan', 'stealth'],
  },
  {
    id: 'shift-walkout',
    name: 'Shift Walkout',
    brief:
      'The textile works has three hundred people and one door. Hold the talks at the gate while the floor walks out with bolts under their coats.',
    kind: 'standard',
    grades: ['D+', 'C'],
    travelBand: 'close',
    durationMinutes: 90,
    spoils: { planks: 30, caps: 30, supplies: 20 },
    leanings: ['parley', 'talk', 'escort'],
  },
  {
    id: 'vault-tape-mirror',
    name: 'Vault Mirror',
    brief:
      'A Combine data vault backs itself up to tape every Thursday. Be the courier who collects the tape, and be very sure of your papers.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'furthest',
    durationMinutes: 120,
    spoils: { caps: 60, highQualityMetal: 10 },
    leanings: ['con', 'wire', 'intel'],
  },
  {
    id: 'pass-book-forgery',
    name: 'Pass Book Forgery',
    brief:
      'Checkpoint wardens carry new pass books with a stripe that glows under the lamp. Get one clean copy and a printer who can learn the trick.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 100,
    spoils: { caps: 50, supplies: 20 },
    leanings: ['con', 'intel'],
  },
  {
    id: 'substation-rewire',
    name: 'Substation Rewire',
    brief:
      'The district substation feeds the Combine barracks and, by accident, three housing blocks. Swap which one is the accident.',
    kind: 'standard',
    grades: ['D+', 'C+'],
    travelBand: 'further',
    durationMinutes: 120,
    spoils: { scrap: 30, highQualityMetal: 15, oil: 20 },
    leanings: ['wire', 'repair', 'plan'],
  },
  {
    id: 'customs-canal-dredge',
    name: 'Canal Dredge',
    brief:
      'The canal bed under the old customs bridge is thick with crates the Combine dumped rather than declared. Wear boots you do not like.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { scrap: 40, planks: 20, highQualityMetal: 5 },
    leanings: ['salvage', 'haul'],
  },
  {
    id: 'ward-transfer',
    name: 'Ward Transfer',
    brief:
      'Four detainees lie under guard in the Combine hospital. Move them to your own ward on gurneys, with forms, before the guard change notices.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 110,
    spoils: { supplies: 50, caps: 30 },
    leanings: ['medic', 'escort', 'con'],
  },
  {
    id: 'freight-yard-tally',
    name: 'Freight Yard Tally',
    brief:
      'Night freight rolls in with manifests that do not match. Work out which wagon is short on paper and heavy on the scale, then lighten it.',
    kind: 'standard',
    grades: ['D', 'C'],
    travelBand: 'furthest',
    durationMinutes: 90,
    spoils: { oil: 30, scrap: 30, highQualityMetal: 10 },
    leanings: ['intel', 'haul', 'road'],
  },
  {
    id: 'dock-crane-cab',
    name: 'Crane Cab',
    brief:
      'The dock crane cab is sixty metres up and holds the only key to the container lockout. Someone has to climb. Someone has to hold the ladder.',
    kind: 'standard',
    grades: ['D+', 'C+'],
    travelBand: 'further',
    durationMinutes: 100,
    spoils: { highQualityMetal: 20, scrap: 40 },
    leanings: ['climb', 'salvage'],
  },
  {
    id: 'silo-mast-tap',
    name: 'Mast Tap',
    brief:
      'Patrol radio runs through a mast on the old grain silo. Hang a box on it that listens and says nothing, then come down quietly.',
    kind: 'standard',
    grades: ['D', 'C-'],
    travelBand: 'further',
    durationMinutes: 70,
    spoils: { caps: 30, scrap: 20 },
    leanings: ['wire', 'climb', 'stealth'],
  },
  {
    id: 'levy-ledger',
    name: 'Levy Ledger',
    brief:
      'The levy office charges your street double and writes down single. Somebody patient can find the difference and sell it back to them.',
    kind: 'standard',
    grades: ['D-', 'C'],
    travelBand: 'close',
    durationMinutes: 50,
    spoils: { caps: 60, supplies: 10 },
    leanings: ['intel', 'talk'],
  },
  {
    id: 'night-market-mediation',
    name: 'Market Mediation',
    brief:
      'Two stall bosses at the night market are one insult from a knife fight that would bring the Combine down on everyone. Sit them down.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 45,
    spoils: { caps: 40, supplies: 30 },
    leanings: ['parley', 'talk'],
  },
  {
    id: 'flood-quarter-dressings',
    name: 'Back Road Run',
    brief:
      'A medic crew in the flood quarter is out of dressings. The Combine roads are watched. The old service tunnels are not, if you can read them.',
    kind: 'standard',
    grades: ['D', 'C'],
    travelBand: 'furthest',
    durationMinutes: 80,
    spoils: { supplies: 60, caps: 10 },
    leanings: ['road', 'medic', 'escort'],
  },
  {
    id: 'glassworks-kiln-restart',
    name: 'Kiln Restart',
    brief:
      'The co-op glassworks went cold when the Combine cut its gas. Relight it off a tapped line and it pays you in whatever it can make.',
    kind: 'standard',
    grades: ['D+', 'C'],
    travelBand: 'further',
    durationMinutes: 120,
    spoils: { planks: 20, scrap: 30, caps: 20, oil: 20 },
    leanings: ['repair', 'breach', 'plan'],
  },
  {
    id: 'depot-drain-grate',
    name: 'Grate Cutting',
    brief:
      'The storm drain under the ration depot has a grate welded shut after the last riot. Cut it open, and remember which way the water runs.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 40,
    spoils: { supplies: 30, scrap: 20 },
    leanings: ['breach', 'salvage'],
  },
  {
    id: 'clerk-quiet-word',
    name: 'Quiet Word',
    brief:
      'A Combine clerk wants out and has a name to trade for it. Meet her somewhere public, look ordinary, and bring a coat she can leave in.',
    kind: 'standard',
    grades: ['D', 'C-'],
    travelBand: 'further',
    durationMinutes: 45,
    spoils: { caps: 50, supplies: 10 },
    leanings: ['talk', 'intel', 'stealth'],
  },
  {
    id: 'listening-van-strip',
    name: 'Van Stripping',
    brief:
      'A Combine listening van broke down on Mercer Street and its crew went for lunch. The kit inside is worth more than the street.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { highQualityMetal: 20, scrap: 40, caps: 10 },
    leanings: ['salvage', 'wire', 'chrome'],
  },
  {
    id: 'drone-hangar-rotors',
    name: 'Drone Hangar',
    brief:
      'The Combine keeps its patrol drones in a hangar on the canal. Loosen enough rotors and the sky over the market goes quiet for a month.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 130,
    spoils: { scrap: 40, highQualityMetal: 15, oil: 10 },
    leanings: ['repair', 'stealth', 'climb'],
  },
  {
    id: 'implant-registry-edit',
    name: 'Implant Registry',
    brief:
      'Every licensed implant has a serial in the Combine registry. Unlicensed ones get a visit. Edit the registry and the visits stop.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'furthest',
    durationMinutes: 150,
    spoils: { caps: 50, highQualityMetal: 10 },
    leanings: ['chrome', 'wire', 'intel'],
  },
  {
    id: 'strike-fund-drop',
    name: 'Strike Fund Drop',
    brief:
      'The dockers are three weeks out. Their fund sits in a union hall the wardens watch. Get the caps in without them looking like caps.',
    kind: 'standard',
    grades: ['D', 'C'],
    travelBand: 'further',
    durationMinutes: 70,
    spoils: { caps: 50, supplies: 30 },
    leanings: ['con', 'escort', 'road'],
  },
  {
    id: 'condemned-block',
    name: 'Condemned Block',
    brief:
      'The Combine has marked Harrow Court for demolition next month. Strip the timber and pipes first, then help the last tenants move out.',
    kind: 'standard',
    grades: ['D-', 'C+'],
    travelBand: 'close',
    durationMinutes: 100,
    spoils: { planks: 50, scrap: 30 },
    leanings: ['salvage', 'haul', 'escort'],
  },
  {
    id: 'water-lab-reagents',
    name: 'Reagent Lift',
    brief:
      'A Combine water lab keeps enough chlorine and nitrate for a small war. Take the small war home before somebody else does.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 120,
    spoils: { supplies: 30, oil: 20, highQualityMetal: 10 },
    leanings: ['breach', 'stealth', 'haul'],
  },
  {
    id: 'customs-seal-borrow',
    name: 'Customs Seals',
    brief:
      'Customs seals crates at the canal gate with wax and a brass stamp. Borrow the stamp for one night and a dozen crates were always inspected.',
    kind: 'standard',
    grades: ['D', 'C-'],
    travelBand: 'close',
    durationMinutes: 50,
    spoils: { caps: 40, planks: 20 },
    leanings: ['con', 'plan'],
  },
  {
    id: 'morgue-burial-detail',
    name: 'Burial Detail',
    brief:
      'The Combine pays crews to clear the morgue after a sweep. The families pay more to know who came in. Keep a careful list.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { caps: 40, supplies: 20 },
    leanings: ['medic', 'intel', 'talk'],
  },
  {
    id: 'flyover-scaffold',
    name: 'Overpass Scaffold',
    brief:
      'Contractors walked off the flyover job and left the scaffolding up. It comes down in steel tubes, ninety metres above the traffic.',
    kind: 'standard',
    grades: ['D+', 'C+'],
    travelBand: 'further',
    durationMinutes: 110,
    spoils: { highQualityMetal: 20, scrap: 40, planks: 10 },
    leanings: ['climb', 'salvage', 'haul'],
  },
  {
    id: 'flood-shelter-stock',
    name: 'Shelter Stock',
    brief:
      'The flood shelter under the transit hub has cots for four hundred and food for forty. Find the rest before the rains start.',
    kind: 'standard',
    grades: ['D-', 'C'],
    travelBand: 'furthest',
    durationMinutes: 90,
    spoils: { supplies: 60, planks: 20 },
    leanings: ['haul', 'road', 'plan'],
  },
  {
    id: 'plaza-screen-hijack',
    name: 'Screen Hijack',
    brief:
      'The plaza screens loop the same Combine anthem from six till midnight. Give them one evening of something else. Wear hoods.',
    kind: 'standard',
    grades: ['D+', 'C'],
    travelBand: 'close',
    durationMinutes: 75,
    spoils: { caps: 40, scrap: 20 },
    leanings: ['wire', 'climb', 'con'],
  },
  {
    id: 'warden-arrears',
    name: 'Warden Arrears',
    brief:
      'A checkpoint warden has not been paid in two months and is starting to say so. Make him an offer his sergeant cannot match.',
    kind: 'standard',
    grades: ['D', 'C-'],
    travelBand: 'close',
    durationMinutes: 40,
    spoils: { caps: 50, supplies: 20 },
    leanings: ['talk', 'parley', 'muscle'],
  },
  {
    id: 'lender-rate-review',
    name: 'Rate Review',
    brief:
      'A Combine licensed lender charges forty per cent to people who owe him nothing. Explain the new rate to him. Loudly, in his office.',
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 35,
    spoils: { caps: 60 },
    leanings: ['muscle', 'chrome'],
  },
  {
    id: 'pulp-mill-night',
    name: 'Pulp Mill Night',
    brief:
      'The pulp mill runs one night shift and burns its offcuts. Bring trucks, a driver who knows the ring road, and a story for the gate.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'furthest',
    durationMinutes: 160,
    spoils: { planks: 60, oil: 20 },
    leanings: ['haul', 'road', 'con'],
  },
  {
    id: 'siding-fuel-tender',
    name: 'Fuel Tender Tap',
    brief:
      'A diesel tender waits on the siding behind the depot for an engine that is two days late. Two days is a lot of jerrycans.',
    kind: 'standard',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 90,
    spoils: { oil: 60, scrap: 10 },
    leanings: ['haul', 'plan', 'stealth'],
  },
  {
    id: 'detention-letter-run',
    name: 'Letter Run',
    brief:
      "The detention block allows no post. A guard's cousin carries letters in for a fee and out for a bigger one. Carry both ways.",
    kind: 'standard',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 40,
    spoils: { caps: 30, supplies: 30 },
    leanings: ['con', 'talk'],
  },
  {
    id: 'kellet-street-triage',
    name: 'Street Triage',
    brief:
      'The Combine cleared Kellet Market with batons an hour ago. Nobody is coming for the people still on the ground but you.',
    kind: 'standard',
    grades: ['D-', 'C-'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { supplies: 50, caps: 10 },
    leanings: ['medic', 'escort'],
  },

  // Battles: Combine squads, wardens, depot guards and rival crews with real guns.
  {
    id: 'grain-depot-gate',
    name: 'Depot Gate Rush',
    brief:
      'Two guards at the Combine grain depot, one gate, one lorry already inside. Hold the gate until the lorry comes back out full.',
    kind: 'battle',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { supplies: 50, caps: 10 },
    leanings: ['fight'],
  },
  {
    id: 'checkpoint-nine',
    name: 'Checkpoint Nine',
    brief:
      'Wardens hold Checkpoint Nine with a shotgun and a radio. Take the radio first, then hold the post until the carts are through.',
    kind: 'battle',
    grades: ['D-', 'D+'],
    travelBand: 'further',
    durationMinutes: 40,
    spoils: { caps: 30, supplies: 30 },
    leanings: ['fight'],
  },
  {
    id: 'tannery-yard-dispute',
    name: 'Yard Dispute',
    brief:
      'The Pike crew says the scrapyard behind the tannery is theirs. They have pipes and two pistols. You have a claim and some friends.',
    kind: 'battle',
    grades: ['D-', 'D'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { scrap: 50, caps: 10 },
    leanings: ['fight'],
  },
  {
    id: 'patrol-barricade',
    name: 'Squad Ambush',
    brief:
      'A three man Combine patrol walks the same route every night at ten. Tonight the route ends at a barricade you built.',
    kind: 'battle',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 45,
    spoils: { caps: 30, supplies: 20, highQualityMetal: 5 },
    leanings: ['fight'],
  },
  {
    id: 'free-clinic-stand',
    name: 'Clinic Stand',
    brief:
      "A rival crew is coming for the free clinic's stock. Stand in the doorway with the nurses behind you and make them pay for every step.",
    kind: 'battle',
    grades: ['D-', 'D'],
    travelBand: 'close',
    durationMinutes: 40,
    spoils: { supplies: 50 },
    leanings: ['fight'],
  },
  {
    id: 'bread-line-guard',
    name: 'Bread Line Guard',
    brief:
      'The Combine hands out bread at the Varley gate and a rival crew takes it back off people round the corner. Go and stand round the corner.',
    kind: 'battle',
    grades: ['D-', 'D+'],
    travelBand: 'close',
    durationMinutes: 45,
    spoils: { supplies: 60 },
    leanings: ['fight'],
  },
  {
    id: 'platform-four-papers',
    name: 'Platform Brawl',
    brief:
      'A Combine squad is checking papers on Platform Four. Half the people on it have none. Start the argument the squad cannot finish.',
    kind: 'battle',
    grades: ['D', 'C-'],
    travelBand: 'further',
    durationMinutes: 60,
    spoils: { caps: 40, supplies: 20 },
    leanings: ['fight'],
  },
  {
    id: 'tool-barge-boarding',
    name: 'Barge Boarding',
    brief:
      'An armed barge carries confiscated tools up the canal twice a week. Board it at the lock while its guards are looking at the water.',
    kind: 'battle',
    grades: ['D', 'C-'],
    travelBand: 'further',
    durationMinutes: 70,
    spoils: { scrap: 30, planks: 20, highQualityMetal: 10 },
    leanings: ['fight'],
  },
  {
    id: 'bonded-store-raid',
    name: 'Bonded Store Raid',
    brief:
      'The bonded warehouse has four guards on days and two at night. Go at night. Bring bolt cutters and someone who does not flinch.',
    kind: 'battle',
    grades: ['D', 'D+'],
    travelBand: 'further',
    durationMinutes: 50,
    spoils: { supplies: 30, oil: 20, caps: 10 },
    leanings: ['fight'],
  },
  {
    id: 'footbridge-toll',
    name: 'Bridge Toll',
    brief:
      'A rival crew has put a toll on the only footbridge to the canal market. Bring the toll down to nothing and keep it there.',
    kind: 'battle',
    grades: ['D', 'C-'],
    travelBand: 'close',
    durationMinutes: 50,
    spoils: { caps: 40, supplies: 20 },
    leanings: ['fight'],
  },
  {
    id: 'tanner-row-shield-line',
    name: 'Shield Line',
    brief:
      'A riot squad is pushing down Tanner Row with shields locked. Break the line at the corner before it reaches the housing blocks.',
    kind: 'battle',
    grades: ['D+', 'C'],
    travelBand: 'close',
    durationMinutes: 80,
    spoils: { caps: 30, supplies: 30 },
    leanings: ['fight'],
  },
  {
    id: 'warden-payroll-car',
    name: 'Payroll Car',
    brief:
      'The Combine pays its wardens from an armoured car that stops at six posts. Stop it at a seventh. The guards inside will object.',
    kind: 'battle',
    grades: ['D+', 'C'],
    travelBand: 'furthest',
    durationMinutes: 90,
    spoils: { caps: 70, highQualityMetal: 5 },
    leanings: ['fight'],
  },
  {
    id: 'bus-garage-war',
    name: 'Garage War',
    brief:
      'The Sable crew moved into the old bus garage with rifles and a grudge. The garage has fuel. Move them out and keep the fuel.',
    kind: 'battle',
    grades: ['D+', 'C-'],
    travelBand: 'further',
    durationMinutes: 70,
    spoils: { oil: 50, scrap: 20 },
    leanings: ['fight'],
  },
  {
    id: 'court-holding-cells',
    name: 'Court Cells',
    brief:
      'Your runner sits in the court holding cells until morning, when the Combine will lose his paperwork and him with it. Go in before then.',
    kind: 'battle',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 120,
    spoils: { caps: 30, supplies: 30 },
    leanings: ['fight'],
  },
  {
    id: 'combine-motor-pool',
    name: 'Motor Pool',
    brief:
      'The Combine motor pool has a gun post on the roof and six trucks below it. Take the post, then take your pick of the trucks.',
    kind: 'battle',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 140,
    spoils: { oil: 40, scrap: 30, highQualityMetal: 15 },
    leanings: ['fight'],
  },
  {
    id: 'hale-street-vault',
    name: 'Vault Guard',
    brief:
      'The Hale Street data vault has an armoured guard squad with orders to wipe the drives if pressed. Press faster than they can wipe.',
    kind: 'battle',
    grades: ['C', 'C+'],
    travelBand: 'furthest',
    durationMinutes: 180,
    spoils: { caps: 50, highQualityMetal: 15 },
    leanings: ['fight'],
  },
  {
    id: 'iron-saints-rent',
    name: 'Iron Saints',
    brief:
      'The Iron Saints have real rifles now, from somewhere, and they are collecting rent on your street. Find the somewhere after the fight.',
    kind: 'battle',
    grades: ['C-', 'C+'],
    travelBand: 'close',
    durationMinutes: 100,
    spoils: { caps: 40, scrap: 20, highQualityMetal: 10 },
    leanings: ['fight'],
  },
  {
    id: 'watchtower-seven',
    name: 'Watchtower Seven',
    brief:
      'Watchtower Seven covers the bridge with a mounted gun and three wardens on rotation. Hit it at the handover, when there are six.',
    kind: 'battle',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 150,
    spoils: { caps: 30, supplies: 20, highQualityMetal: 10 },
    leanings: ['fight'],
  },
  {
    id: 'east-ward-lockdown',
    name: 'Ward Lockdown',
    brief:
      'Combine security has locked down the east ward to find one patient. Get her out before they reach her floor. The corridors are narrow.',
    kind: 'battle',
    grades: ['C', 'C+'],
    travelBand: 'further',
    durationMinutes: 160,
    spoils: { supplies: 50, caps: 20 },
    leanings: ['fight'],
  },
  {
    id: 'rail-depot-armoury-shed',
    name: 'Rail Depot Guard',
    brief:
      'The rail depot keeps a garrison of twelve and a locked shed of rifles. The shed is the point. The twelve are in the way.',
    kind: 'battle',
    grades: ['C-', 'C+'],
    travelBand: 'furthest',
    durationMinutes: 200,
    spoils: { highQualityMetal: 15, scrap: 40, caps: 10 },
    leanings: ['fight'],
  },
];
