import type { MissionTemplate } from '../missions.js';

/** Mayhem, S- to S+, and jobs that run across the bands: legendary fights, grand heists, long cons. */
export const MAYHEM_JOBS: readonly MissionTemplate[] = [
  // Mayhem fights, S- to S+.
  {
    id: 'spire-crown',
    name: 'The Spire Crown',
    brief:
      'The top floor of the Spire has never been taken. It has also never been tried by anybody who did not work there. Go up and change that.',
    kind: 'battle',
    grades: ['S-', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 720,
    spoils: { highQualityMetal: 20, caps: 60 },
    leanings: ['fight'],
  },
  {
    id: 'iron-choir',
    name: 'The Iron Choir',
    brief:
      'The Combine heavy armour squad sings on the radio before it moves in. Nobody has heard the second verse and lived. Be the first.',
    kind: 'battle',
    grades: ['S', 'S+'],
    travelBand: 'further',
    durationMinutes: 900,
    spoils: { highQualityMetal: 40, scrap: 30 },
    leanings: ['fight'],
  },
  {
    id: 'stadium-garrison',
    name: 'Stadium Garrison',
    brief:
      'Nine hundred Combine regulars sleep in the old stadium. You do not need to beat all of them, only the ones who wake up.',
    kind: 'battle',
    grades: ['S-', 'S'],
    travelBand: 'further',
    durationMinutes: 600,
    spoils: { supplies: 40, oil: 20, caps: 30 },
    leanings: ['fight'],
  },
  {
    id: 'black-lantern',
    name: 'The Black Lantern',
    brief:
      'Parents tell children the Black Lantern takes the ones who miss curfew. It is a gunship, it is real, and tonight it is parked.',
    kind: 'battle',
    grades: ['S-', 'S+'],
    travelBand: 'close',
    durationMinutes: 480,
    spoils: { highQualityMetal: 30, oil: 40 },
    leanings: ['fight'],
  },
  {
    id: 'warden-hall',
    name: 'Warden Hall',
    brief:
      'The Warden has run the city prisons for thirty years from one room. Take the room. The keys on his belt open every cell below it.',
    kind: 'battle',
    grades: ['S', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 1000,
    spoils: { caps: 50, supplies: 30 },
    leanings: ['fight'],
  },
  {
    id: 'dreadnought-yard',
    name: 'Dreadnought Yard',
    brief:
      'The Combine is building a walking tank in the east yard. It is not finished yet. This is the only week it loses a fight.',
    kind: 'battle',
    grades: ['S-', 'S'],
    travelBand: 'furthest',
    durationMinutes: 800,
    spoils: { highQualityMetal: 50, scrap: 40, oil: 10 },
    leanings: ['fight'],
  },
  {
    id: 'glass-legion',
    name: 'The Glass Legion',
    brief:
      'Chromed shock troops with mirror visors, hired from a foreign firm and rented to the Combine by the hour. Make the hours expensive.',
    kind: 'battle',
    grades: ['S-', 'S+'],
    travelBand: 'further',
    durationMinutes: 700,
    spoils: { highQualityMetal: 30, caps: 40 },
    leanings: ['fight'],
  },
  {
    id: 'storm-the-mint',
    name: 'Storm the Mint',
    brief:
      'The Combine prints its caps in a bunker under the Treasury. Every guard there is paid in them and knows exactly how many there are.',
    kind: 'battle',
    grades: ['S', 'S+'],
    travelBand: 'further',
    durationMinutes: 960,
    spoils: { caps: 90, highQualityMetal: 10 },
    leanings: ['fight'],
  },
  {
    id: 'last-bridge',
    name: 'The Last Bridge',
    brief:
      'The river bridge is the only way the Combine moves armour north. Hold it for one night and the whole front waits on you.',
    kind: 'battle',
    grades: ['S-', 'S'],
    travelBand: 'further',
    durationMinutes: 540,
    spoils: { oil: 30, supplies: 30, planks: 20 },
    leanings: ['fight'],
  },
  {
    id: 'hound-kennels',
    name: 'The Hound Kennels',
    brief:
      'The Combine breeds its tracker dogs with implants in the jaw. The kennels also hold the handlers, who are worse. Clear the lot.',
    kind: 'battle',
    grades: ['S-', 'S+'],
    travelBand: 'close',
    durationMinutes: 600,
    spoils: { scrap: 30, supplies: 30, highQualityMetal: 15 },
    leanings: ['fight'],
  },
  {
    id: 'jammer-tower',
    name: 'The Jammer Tower',
    brief:
      'The tower that jams every radio in the city is guarded like a king. Bring it down and the whole city can talk for a day.',
    kind: 'battle',
    grades: ['S', 'S+'],
    travelBand: 'further',
    durationMinutes: 840,
    spoils: { highQualityMetal: 25, scrap: 25, caps: 20 },
    leanings: ['fight'],
  },
  {
    id: 'convoy-of-kings',
    name: 'Convoy of Kings',
    brief:
      'Once a year the Combine board rides from the Spire to the coast in forty armoured cars. You get about ninety seconds of road.',
    kind: 'battle',
    grades: ['S-', 'S'],
    travelBand: 'furthest',
    durationMinutes: 480,
    spoils: { caps: 70, oil: 30 },
    leanings: ['fight'],
  },
  {
    id: 'red-quarantine',
    name: 'Red Quarantine',
    brief:
      'The sealed ward on Hollow Street has a plague, a garrison and a lab. The lab is the reason for the other two. Go in masked.',
    kind: 'battle',
    grades: ['S-', 'S+'],
    travelBand: 'close',
    durationMinutes: 660,
    spoils: { supplies: 50, highQualityMetal: 20 },
    leanings: ['fight'],
  },
  {
    id: 'victory-parade',
    name: 'The Victory Parade',
    brief:
      'The Combine is marching its whole army down the Avenue to prove nobody can stop it. Stop it, on camera, in front of everybody.',
    kind: 'battle',
    grades: ['S', 'S+'],
    travelBand: 'close',
    durationMinutes: 1200,
    spoils: { caps: 40, supplies: 30, scrap: 20 },
    leanings: ['fight'],
  },

  // Fights in the lower categories.
  {
    id: 'drone-swatting',
    name: 'Drone Swatting',
    brief:
      'Three Combine patrol drones fly the same loop over the washhouses every hour. Bring them down before they learn a new one.',
    kind: 'battle',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { scrap: 40 },
    leanings: ['fight'],
  },
  {
    id: 'night-market-brawl',
    name: 'Night Market Brawl',
    brief:
      'A Combine sweep team is kicking over stalls at the night market. The stall owners have noticed you have more friends than they do.',
    kind: 'battle',
    grades: ['F', 'E-'],
    travelBand: 'close',
    durationMinutes: 15,
    spoils: { caps: 20, supplies: 20 },
    leanings: ['fight'],
  },
  {
    id: 'tile-works-picket',
    name: 'The Picket Line',
    brief:
      'Strikers at the tile works have held the gate for a week. The Combine sends men with sticks at shift change. Stand with them.',
    kind: 'battle',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { supplies: 30, planks: 10 },
    leanings: ['fight'],
  },
  {
    id: 'tram-depot-fight',
    name: 'Tram Depot Fight',
    brief:
      'The Combine is turning the tram depot into a barracks. Right now it is half built and held by a platoon that would rather be elsewhere.',
    kind: 'battle',
    grades: ['D-', 'D+'],
    travelBand: 'further',
    durationMinutes: 60,
    spoils: { planks: 30, scrap: 30 },
    leanings: ['fight'],
  },
  {
    id: 'hold-the-clinic',
    name: 'Hold the Clinic',
    brief:
      'A free clinic in the Weave gets cleared at dawn. The doctors are packing. Buy them the hours they need to get the patients out.',
    kind: 'battle',
    grades: ['D', 'C-'],
    travelBand: 'close',
    durationMinutes: 90,
    spoils: { supplies: 40, caps: 10 },
    leanings: ['fight'],
  },
  {
    id: 'radio-hill',
    name: 'Radio Hill',
    brief:
      'Whoever holds Radio Hill hears the whole south side. The Combine holds it with a squad and a machine gun. Only one is a problem.',
    kind: 'battle',
    grades: ['C-', 'C+'],
    travelBand: 'further',
    durationMinutes: 150,
    spoils: { highQualityMetal: 10, scrap: 20, caps: 20 },
    leanings: ['fight'],
  },
  {
    id: 'canal-locks',
    name: 'The Canal Locks',
    brief:
      'The Combine floods the low districts when it wants them empty. Engineers and a company of guards work the lock gates. Take the gates.',
    kind: 'battle',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 240,
    spoils: { oil: 20, planks: 20, supplies: 30 },
    leanings: ['fight'],
  },
  {
    id: 'tithe-barracks',
    name: 'Tithe Barracks',
    brief:
      'Every tithe collector sleeps in one barracks on Crown Row. Besiege it and a whole district keeps its money for a month.',
    kind: 'battle',
    grades: ['B', 'A-'],
    travelBand: 'close',
    durationMinutes: 300,
    spoils: { caps: 60, supplies: 20 },
    leanings: ['fight'],
  },
  {
    id: 'cistern-keep',
    name: 'Cistern Keep',
    brief:
      'The great cistern under Old Square holds the district water and a garrison that rations it. Break the siege line and open the taps.',
    kind: 'battle',
    grades: ['B+', 'A'],
    travelBand: 'further',
    durationMinutes: 360,
    spoils: { supplies: 50, scrap: 10 },
    leanings: ['fight'],
  },
  {
    id: 'kestrel-airfield',
    name: 'Kestrel Airfield',
    brief:
      'Six Combine gunships sit at Kestrel field behind two hundred guards. Drain the fuel store and the gunships become heavy sculptures.',
    kind: 'battle',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 600,
    spoils: { oil: 50, highQualityMetal: 20 },
    leanings: ['fight'],
  },

  // Plain work at the very top, A- to S+.
  {
    id: 'chairman-vault',
    name: 'The Chairman Vault',
    brief:
      'The Chairman keeps his private vault forty floors up or two floors down. Nobody knows which. Find out, then find a way in.',
    kind: 'standard',
    grades: ['S-', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 1100,
    spoils: { caps: 80, highQualityMetal: 30 },
    leanings: ['stealth', 'breach', 'plan'],
  },
  {
    id: 'salt-road-caravan',
    name: 'The Salt Road',
    brief:
      'Walk a caravan across the salt flats to the free port and back. No shade, no water, and the Combine pays bandits by the head.',
    kind: 'standard',
    grades: ['A', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 600,
    spoils: { supplies: 50, oil: 30, caps: 20 },
    leanings: ['road', 'haul', 'escort'],
  },
  {
    id: 'board-seat-con',
    name: 'A Seat at the Board',
    brief:
      'Get one of ours seated on the Combine board under a borrowed name. It takes a year of papers and one very good dinner.',
    kind: 'standard',
    grades: ['A+', 'S+'],
    travelBand: 'further',
    durationMinutes: 700,
    spoils: { caps: 90 },
    leanings: ['con', 'talk', 'intel'],
  },
  {
    id: 'drowned-line-dive',
    name: 'The Drowned Line',
    brief:
      'The old metro line flooded with a train still in it, and the train was carrying Combine alloy. Dive for it. Count your air.',
    kind: 'standard',
    grades: ['A-', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 500,
    spoils: { highQualityMetal: 40, scrap: 40 },
    leanings: ['salvage', 'road', 'medic'],
  },
  {
    id: 'northern-dam',
    name: 'The Northern Dam',
    brief:
      'The northern dam powers half the Combine. One quiet engineer at the turbines could send that power our way. Bring rope, it is tall.',
    kind: 'standard',
    grades: ['S-', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 900,
    spoils: { oil: 40, highQualityMetal: 20, supplies: 20 },
    leanings: ['repair', 'climb', 'haul'],
  },
  {
    id: 'ghost-in-the-grid',
    name: 'Ghost in the Grid',
    brief:
      'Live inside the Combine network for a week without being found. Everything you read is worth money to somebody. Leave no footprints.',
    kind: 'standard',
    grades: ['A', 'S'],
    travelBand: 'further',
    durationMinutes: 480,
    spoils: { caps: 50, highQualityMetal: 20 },
    leanings: ['wire', 'stealth', 'intel'],
  },
  {
    id: 'ambassador-swap',
    name: 'The Ambassador',
    brief:
      'A foreign envoy arrives on Thursday with a face nobody here has ever seen. A surgeon owes us a favour. You can guess the rest.',
    kind: 'standard',
    grades: ['A+', 'S+'],
    travelBand: 'close',
    durationMinutes: 800,
    spoils: { caps: 60, supplies: 20 },
    leanings: ['con', 'parley', 'chrome'],
  },
  {
    id: 'cold-archive',
    name: 'The Cold Archive',
    brief:
      'Under the Census office sits the cold archive: every name, debt and lie since the founding. Copy it and keep the cooling running.',
    kind: 'standard',
    grades: ['A-', 'S'],
    travelBand: 'further',
    durationMinutes: 400,
    spoils: { caps: 40, highQualityMetal: 20 },
    leanings: ['intel', 'stealth', 'repair'],
  },
  {
    id: 'hollow-fleet',
    name: 'The Hollow Fleet',
    brief:
      'Past the coast road a whole Combine tanker fleet rusts on a sandbar. Get there before the tide, strip it, and leave before the owners come.',
    kind: 'standard',
    grades: ['S-', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 1000,
    spoils: { oil: 60, highQualityMetal: 30 },
    leanings: ['road', 'salvage', 'haul'],
  },
  {
    id: 'four-gang-truce',
    name: 'The Four Gang Truce',
    brief:
      'Broker a truce between the four biggest gangs in the Weave, so the Combine has nobody left to play off. Bring coffee and patience.',
    kind: 'standard',
    grades: ['A', 'S+'],
    travelBand: 'close',
    durationMinutes: 560,
    spoils: { supplies: 40, caps: 40 },
    leanings: ['parley', 'talk', 'plan'],
  },
  {
    id: 'surgeon-queen',
    name: 'The Surgeon Queen',
    brief:
      'The best implant surgeon in the city wants out of Combine service. She needs a new face, a new clinic and a crew around her all the way.',
    kind: 'standard',
    grades: ['A+', 'S+'],
    travelBand: 'further',
    durationMinutes: 600,
    spoils: { highQualityMetal: 40, supplies: 20 },
    leanings: ['chrome', 'medic', 'escort'],
  },
  {
    id: 'city-broadcast',
    name: 'Every Screen at Once',
    brief:
      'Take every screen in the city for four minutes. The Combine will know who did it by minute five, so have a plan for minute six.',
    kind: 'standard',
    grades: ['S-', 'S+'],
    travelBand: 'close',
    durationMinutes: 720,
    spoils: { caps: 30, scrap: 30, highQualityMetal: 20 },
    leanings: ['wire', 'climb', 'plan'],
  },
  {
    id: 'mile-long-freight',
    name: 'Mile Long Freight',
    brief:
      'Run a Combine freight train to our side of the river on false manifests. The train is a mile long. The papers had better be longer.',
    kind: 'standard',
    grades: ['A-', 'S+'],
    travelBand: 'furthest',
    durationMinutes: 480,
    spoils: { oil: 30, highQualityMetal: 30, planks: 20, scrap: 20 },
    leanings: ['haul', 'road', 'con'],
  },
  {
    id: 'heir-forgery',
    name: 'The Missing Heir',
    brief:
      'A dead board member left an heir nobody has met. Produce one, complete with teeth, school records and a believable grudge.',
    kind: 'standard',
    grades: ['A', 'S-'],
    travelBand: 'further',
    durationMinutes: 360,
    spoils: { caps: 70 },
    leanings: ['con', 'intel', 'talk'],
  },
  {
    id: 'bone-orchard-dig',
    name: 'The Bone Orchard',
    brief:
      'The Combine buried a failed war machine under the old orchard. It is worth more in pieces than it ever was whole. Bring shovels.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'further',
    durationMinutes: 300,
    spoils: { scrap: 40, highQualityMetal: 20 },
    leanings: ['salvage', 'repair', 'haul'],
  },
  {
    id: 'tollgate-treaty',
    name: 'The Tollgate Treaty',
    brief:
      'Two city tollgates have been shooting at each other for a month. Get both sides to one table and leave holding the passage rights.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 280,
    spoils: { caps: 40, supplies: 30 },
    leanings: ['parley', 'talk', 'road'],
  },
  {
    id: 'spine-recall',
    name: 'The Spine Recall',
    brief:
      'The Combine is recalling a bad batch of spine implants by switching them off. Four hundred people are wearing them. Get there first.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'close',
    durationMinutes: 300,
    spoils: { highQualityMetal: 30, caps: 20 },
    leanings: ['chrome', 'medic', 'wire'],
  },
  {
    id: 'paper-regiment',
    name: 'The Paper Regiment',
    brief:
      'Invent a regiment: uniforms, pay records, a colonel with a limp. Once the Combine starts paying it, the wages come to us.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'further',
    durationMinutes: 260,
    spoils: { caps: 50, supplies: 20 },
    leanings: ['con', 'plan', 'intel'],
  },
  {
    id: 'pine-hill-airship',
    name: 'Pine Hill Airship',
    brief:
      'A Combine airship came down in the pine hills and nobody went to look. Somebody should. The alloy frame alone is a fortune.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 400,
    spoils: { highQualityMetal: 40, planks: 20 },
    leanings: ['climb', 'salvage', 'road'],
  },
  {
    id: 'undercity-atlas',
    name: 'The Undercity Atlas',
    brief:
      'Chart the undercity end to end: drains, tunnels, forgotten cellars. The Combine has the only copy. After this, so do we.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'close',
    durationMinutes: 240,
    spoils: { caps: 30, supplies: 20, scrap: 10 },
    leanings: ['intel', 'road', 'stealth'],
  },

  // Plain work that follows a crew up the middle of the ladder.
  {
    id: 'rooftop-greenhouses',
    name: 'Rooftop Greenhouses',
    brief:
      'Rig greenhouses on four roofs the Combine forgot to tax. Keep them watered, keep them quiet and keep the pigeons off.',
    kind: 'standard',
    grades: ['E+', 'C'],
    travelBand: 'close',
    durationMinutes: 45,
    spoils: { supplies: 50, planks: 20 },
    leanings: ['climb', 'repair', 'plan'],
  },
  {
    id: 'roof-to-roof-radio',
    name: 'Roof to Roof Radio',
    brief:
      'Keep a pirate station on air from a different roof every night. Combine vans triangulate in twenty minutes. Nineteen is fine.',
    kind: 'standard',
    grades: ['E+', 'C'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { caps: 20, scrap: 20 },
    leanings: ['wire', 'climb', 'stealth'],
  },
  {
    id: 'flyover-wrecks',
    name: 'Flyover Wrecks',
    brief:
      'Strip the burnt-out cars off the old flyover before the Combine cranes come for them. First there is first paid.',
    kind: 'standard',
    grades: ['E', 'C-'],
    travelBand: 'close',
    durationMinutes: 30,
    spoils: { scrap: 60, oil: 10 },
    leanings: ['salvage', 'haul'],
  },
  {
    id: 'lost-medics',
    name: 'The Lost Medics',
    brief:
      'A Combine field hospital left three medics behind in the flood zone. Find them before the water does, or the Combine.',
    kind: 'standard',
    grades: ['E+', 'C'],
    travelBand: 'further',
    durationMinutes: 50,
    spoils: { supplies: 40, caps: 10 },
    leanings: ['medic', 'road', 'escort'],
  },
  {
    id: 'facade-scaffold',
    name: 'Scaffold Crew',
    brief:
      'The Combine hires day crews to patch the tower facades. Sign on, work the scaffold, and look at what sits behind the windows.',
    kind: 'standard',
    grades: ['E', 'C-'],
    travelBand: 'close',
    durationMinutes: 40,
    spoils: { planks: 30, caps: 20 },
    leanings: ['climb', 'intel', 'repair'],
  },
  {
    id: 'back-room-clinic',
    name: 'Back Room Clinic',
    brief:
      'Staff a back room clinic for the people the Combine hospitals will not see. The work is steady, and so is the bleeding.',
    kind: 'standard',
    grades: ['D-', 'C'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { supplies: 40, caps: 10 },
    leanings: ['medic', 'stealth'],
  },
  {
    id: 'smugglers-bore',
    name: 'Smugglers Bore',
    brief:
      'Dig a tunnel under the district wall with a crew who swear they have done it before. Shore it well. The wall is heavy.',
    kind: 'standard',
    grades: ['D-', 'C+'],
    travelBand: 'close',
    durationMinutes: 60,
    spoils: { planks: 40, scrap: 20 },
    leanings: ['haul', 'repair', 'stealth'],
  },
  {
    id: 'pylon-tap',
    name: 'Pylon Tap',
    brief:
      'Tap the Combine power line where it crosses the rail yard. It hums, it bites, and it pays for itself inside a week.',
    kind: 'standard',
    grades: ['D', 'B-'],
    travelBand: 'further',
    durationMinutes: 60,
    spoils: { oil: 20, scrap: 30 },
    leanings: ['wire', 'repair', 'climb'],
  },
  {
    id: 'blast-quarry',
    name: 'Blast Quarry',
    brief:
      'A quarry outside the wall still has Combine blasting caps in its magazine. Use some to open a new face and carry the rest home.',
    kind: 'standard',
    grades: ['D', 'B-'],
    travelBand: 'further',
    durationMinutes: 60,
    spoils: { scrap: 30, planks: 20, supplies: 10 },
    leanings: ['breach', 'haul', 'salvage'],
  },
  {
    id: 'river-ferry',
    name: 'The Night Ferry',
    brief:
      'Run the night ferry across the river for a month. The fares are small, the cargo under the benches is not, and the harbour police can count.',
    kind: 'standard',
    grades: ['D+', 'B'],
    travelBand: 'further',
    durationMinutes: 90,
    spoils: { caps: 30, oil: 20 },
    leanings: ['road', 'haul', 'talk'],
  },
  {
    id: 'motor-pool-chop',
    name: 'Motor Pool Chop Shop',
    brief:
      'Run a chop shop under the Combine motor pool. Everything they scrap goes out one door and comes back in the other, repainted.',
    kind: 'standard',
    grades: ['D+', 'B'],
    travelBand: 'close',
    durationMinutes: 90,
    spoils: { scrap: 40, oil: 20, caps: 10 },
    leanings: ['repair', 'salvage', 'con'],
  },
  {
    id: 'dock-walkout',
    name: 'Dock Walkout',
    brief:
      'The dockers want to walk out but nobody trusts the organiser. Get all three shifts in one room and keep them there until they agree.',
    kind: 'standard',
    grades: ['D+', 'B-'],
    travelBand: 'further',
    durationMinutes: 80,
    spoils: { supplies: 30, caps: 30 },
    leanings: ['parley', 'plan', 'muscle'],
  },
  {
    id: 'canal-row-mill',
    name: 'Canal Row Mill',
    brief:
      'The old flour mill on Canal Row could feed the district again if somebody fixed the stones and kept the Combine assessors out.',
    kind: 'standard',
    grades: ['D+', 'C+'],
    travelBand: 'further',
    durationMinutes: 90,
    spoils: { supplies: 40, planks: 20 },
    leanings: ['repair', 'plan', 'talk'],
  },
  {
    id: 'debt-slip-ring',
    name: 'The Pawn Ring',
    brief:
      'Buy up Combine debt slips cheap from the pawnshops and sell them back dear. It is entirely legal, which somehow makes it worse.',
    kind: 'standard',
    grades: ['C-', 'B+'],
    travelBand: 'close',
    durationMinutes: 90,
    spoils: { caps: 60 },
    leanings: ['talk', 'intel', 'con'],
  },
  {
    id: 'card-press',
    name: 'The Card Press',
    brief:
      'Print ration cards that scan as real at every Combine counter. The ink is the hard part. The printer owes you a favour.',
    kind: 'standard',
    grades: ['C-', 'B'],
    travelBand: 'close',
    durationMinutes: 120,
    spoils: { supplies: 40, caps: 20 },
    leanings: ['con', 'wire', 'plan'],
  },
  {
    id: 'watch-list-scrub',
    name: 'Clean Records',
    brief:
      'Wipe a hundred names off the Combine watch list before the next census. Each one costs a clerk a small bribe and a large fright.',
    kind: 'standard',
    grades: ['C-', 'B-'],
    travelBand: 'further',
    durationMinutes: 100,
    spoils: { caps: 50 },
    leanings: ['wire', 'intel', 'muscle'],
  },
  {
    id: 'gate-family-papers',
    name: 'Border Papers',
    brief:
      'Walk a family of five through the city gates on papers you made last night. The guard is new and nervous. So are you.',
    kind: 'standard',
    grades: ['C-', 'B'],
    travelBand: 'further',
    durationMinutes: 70,
    spoils: { caps: 40, supplies: 10 },
    leanings: ['con', 'escort', 'talk'],
  },
  {
    id: 'bent-inspector',
    name: 'The Bent Inspector',
    brief:
      'A building inspector takes Combine money to condemn our blocks. Find out who pays him, then pay him more, or lean on him.',
    kind: 'standard',
    grades: ['C', 'B'],
    travelBand: 'further',
    durationMinutes: 120,
    spoils: { caps: 40, planks: 10 },
    leanings: ['talk', 'intel', 'muscle'],
  },
  {
    id: 'frozen-canal-run',
    name: 'The Ice Road',
    brief:
      'Drive supplies up the frozen canal to the northern camps. The ice holds until it does not. The camps pay in oil.',
    kind: 'standard',
    grades: ['C', 'B+'],
    travelBand: 'furthest',
    durationMinutes: 150,
    spoils: { oil: 40, supplies: 20 },
    leanings: ['road', 'haul', 'escort'],
  },
  {
    id: 'backstreet-chrome',
    name: 'Backstreet Chrome',
    brief:
      'Fit black market implants for runners who cannot afford the Combine price. Sterilise everything. The last surgeon forgot.',
    kind: 'standard',
    grades: ['C', 'B+'],
    travelBand: 'close',
    durationMinutes: 150,
    spoils: { highQualityMetal: 15, caps: 30 },
    leanings: ['chrome', 'medic'],
  },
];
