import type { MissionTemplate } from '../missions.js';

/** The street band, F- to E+: gutters, rooftops and back rooms, paid in whatever the block has spare. */
export const STREET_JOBS: readonly MissionTemplate[] = [
  {
    id: 'pipe-crawl',
    name: 'Pipe Crawl',
    brief:
      'The storm drains under Coldwater still carry copper nobody has counted. Go in low, come out filthy, and do not light anything.',
    kind: 'standard',
    grades: ['F', 'E-'],
    travelBand: 'close',
    durationMinutes: 8,
    spoils: { scrap: 30, caps: 6 },
    leanings: ['salvage', 'climb'],
  },
  {
    id: 'stall-sweep',
    name: 'Stall Sweep',
    brief:
      'The night market packs up at four and leaves half its stock in the gutter. Pick through it before the street cleaners do.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 4,
    spoils: { supplies: 20, caps: 5 },
    leanings: ['haul', 'salvage'],
  },
  {
    id: 'doorbell-harvest',
    name: 'Doorbell Harvest',
    brief:
      'Every tenement on Mercy Row has a dead intercom panel by the door. The boards inside still sell. Unscrew quietly, residents sleep light.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 6,
    spoils: { scrap: 20, caps: 10 },
    leanings: ['wire', 'stealth'],
  },
  {
    id: 'rooftop-tanks',
    name: 'Rooftop Tanks',
    brief:
      'Rain tanks on the Kestrel Block roofs are full after the storm. Nobody up there to argue. Twelve floors of stairs each way.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 6,
    spoils: { supplies: 25, caps: 4 },
    leanings: ['climb', 'haul'],
  },
  {
    id: 'clinic-queue',
    name: 'Clinic Queue',
    brief:
      'The free clinic on Tallow Lane pays in dressings and pills for anyone who will keep the queue calm and help with the walking wounded.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { supplies: 30 },
    leanings: ['medic', 'talk'],
  },
  {
    id: 'pawn-run',
    name: 'Pawn Run',
    brief:
      "A widow wants her husband's watch sold at a price she can live with. The pawnbroker on Ash Street has never paid a fair price in his life.",
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { caps: 25, supplies: 5 },
    leanings: ['talk', 'con'],
  },
  {
    id: 'arcade-strip',
    name: 'Arcade Strip',
    brief:
      'The Neon Palace arcade shut when the Combine put a tax on fun. The cabinets inside are still full of boards, screens and coin.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { scrap: 20, caps: 12 },
    leanings: ['salvage', 'repair'],
  },
  {
    id: 'dock-shift',
    name: 'Dock Shift',
    brief:
      'A barge came in heavy and the dockers walked out. The foreman pays by the crate and does not ask whose crew you are.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { caps: 15, supplies: 10 },
    leanings: ['haul', 'plan'],
  },
  {
    id: 'shift-count',
    name: 'Shift Count',
    brief:
      'A clerk in the records office pays for a count of the patrol changes on Lantern Street. Sit in a window, drink tea, write it all down.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 8,
    spoils: { caps: 15 },
    leanings: ['intel', 'plan'],
  },
  {
    id: 'bike-courier',
    name: 'Bike Courier',
    brief:
      'A pharmacist needs insulin across four districts before the checkpoints change shift. The bike has one brake. Use it sparingly.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'further',
    durationMinutes: 6,
    spoils: { supplies: 15, caps: 10 },
    leanings: ['road', 'medic'],
  },
  {
    id: 'neon-lift',
    name: 'Neon Lift',
    brief:
      'The dead neon over the Ho Lung noodle bar is worth more than the bar. Get up there with a spanner and a friend holding the ladder.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { scrap: 20, caps: 8 },
    leanings: ['climb', 'salvage'],
  },
  {
    id: 'soup-line',
    name: 'Soup Line',
    brief:
      'The church soup line turns into a brawl most nights. The priest pays in bread for anyone who can keep it a line.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 6,
    spoils: { supplies: 25 },
    leanings: ['parley', 'talk'],
  },
  {
    id: 'paper-kitchen',
    name: 'Paper Kitchen',
    brief:
      'A family needs work passes by Thursday. The printer in the laundry basement has the stamps, but only you know how to age the paper.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 15,
    spoils: { caps: 20, supplies: 5 },
    leanings: ['con', 'intel'],
  },
  {
    id: 'squat-boiler',
    name: 'Squat Boiler',
    brief:
      'The squat on Corder Street has no heat and forty children. Fix the boiler and they will feed you for a week.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { supplies: 20, planks: 10 },
    leanings: ['repair', 'haul'],
  },
  {
    id: 'rent-reminder',
    name: 'Rent Reminder',
    brief:
      'A tenant stopped paying because the landlord stopped fixing. Go and settle it. Both of them are offering you money to pick their side.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 8,
    spoils: { caps: 20 },
    leanings: ['muscle', 'talk'],
  },
  {
    id: 'substation-patch',
    name: 'Substation Patch',
    brief:
      'The Holloway substation drops the block every evening. The Combine sends no engineers below the ninth tier. The residents will pay you.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 18,
    spoils: { caps: 15, scrap: 10 },
    leanings: ['repair', 'wire'],
  },
  {
    id: 'back-room-chrome',
    name: 'Back Room Chrome',
    brief:
      'A street doc needs a steady pair of hands for an arm fitting. The patient is awake. The anaesthetic ran out last week.',
    kind: 'standard',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 20,
    spoils: { supplies: 15, caps: 15, highQualityMetal: 3 },
    leanings: ['chrome', 'medic'],
  },
  {
    id: 'morgue-chrome',
    name: 'Morgue Chrome',
    brief:
      'The morgue on Grey Street keeps bodies three days before the incinerator. Their implants do not have to go with them.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 16,
    spoils: { scrap: 10, highQualityMetal: 5, caps: 10 },
    leanings: ['chrome', 'salvage', 'stealth'],
  },
  {
    id: 'tram-yard',
    name: 'Tram Yard',
    brief:
      'Forty trams rust in the Eastgate yard, waiting on a Combine budget that will never come. Their seats, rails and motors are waiting on you.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'further',
    durationMinutes: 12,
    spoils: { scrap: 30, planks: 8 },
    leanings: ['salvage', 'haul'],
  },
  {
    id: 'signal-box',
    name: 'Signal Box',
    brief:
      'The old signal box in the rail yard still logs every Combine freight train. Copy the ledger and the timetable is yours to sell.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'further',
    durationMinutes: 18,
    spoils: { caps: 20 },
    leanings: ['wire', 'intel'],
  },
  {
    id: 'pigeon-loft',
    name: 'Pigeon Loft',
    brief:
      'Old Mo sends messages by pigeon from the dye works roof, where the Combine cannot read them. Carry his feed up. Carry his notes down.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { supplies: 15, caps: 5 },
    leanings: ['climb', 'road'],
  },
  {
    id: 'fence-drop',
    name: 'Fence Drop',
    brief:
      'A fence in the arcade basement will take the stolen radios, but only from someone he has never seen. Borrow a coat and a new name.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { caps: 25 },
    leanings: ['con', 'talk'],
  },
  {
    id: 'flood-bail',
    name: 'Flood Bail',
    brief:
      'The basement flats on Weir Street flooded again. Bail out the water, save what floats, keep what nobody claims.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { supplies: 10, scrap: 15, planks: 5 },
    leanings: ['haul', 'repair'],
  },
  {
    id: 'scaffold-strip',
    name: 'Scaffold Strip',
    brief:
      'The Combine started a tower on Pallet Hill and ran out of money at the fourth floor. The scaffold boards are still up there.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 14,
    spoils: { planks: 30 },
    leanings: ['climb', 'haul'],
  },
  {
    id: 'barter-stall',
    name: 'Barter Stall',
    brief:
      'Run a stall at the Sunday swap for a sick trader. Buy low, sell high to the tourists from the upper tiers, and keep a tenth.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { caps: 20, supplies: 10 },
    leanings: ['talk', 'plan'],
  },
  {
    id: 'missing-boy',
    name: 'Missing Boy',
    brief:
      'A mother on Cistern Row lost her son to the arcades three days ago. Find him before the recruiters on the fifth floor do.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 15,
    spoils: { caps: 10, supplies: 10 },
    leanings: ['intel', 'road'],
  },
  {
    id: 'gas-main-tap',
    name: 'Gas Main Tap',
    brief:
      'The Combine capped the gas main to the Smoke Street tenements. Uncapping it takes a torch, a wrench and nerve. Tenants pay in fuel.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 18,
    spoils: { oil: 20, caps: 10 },
    leanings: ['breach', 'repair'],
  },
  {
    id: 'sealed-flat-safe',
    name: 'Safe Crack',
    brief:
      'A dead loan shark left a safe in a flat the Combine has sealed. Get in through the neighbours, blow it softly, share with the neighbours.',
    kind: 'standard',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 20,
    spoils: { caps: 30, highQualityMetal: 2 },
    leanings: ['breach', 'stealth'],
  },
  {
    id: 'shortcut-map',
    name: 'Shortcut Map',
    brief:
      'Sketch the alleys and cut-throughs between the docks and the market that Combine patrol maps do not show. A smuggler is buying.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'further',
    durationMinutes: 14,
    spoils: { caps: 20 },
    leanings: ['road', 'intel'],
  },
  {
    id: 'roof-garden',
    name: 'Roof Garden',
    brief:
      'A Combine clerk grows tomatoes on his office roof. They are the only fresh food for three districts. He counts them every morning.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { supplies: 25 },
    leanings: ['climb', 'stealth'],
  },
  {
    id: 'canal-drums',
    name: 'Canal Drums',
    brief:
      'Six drums of cooking oil fell off a Combine lorry into the canal. They float. Get them to the bank before the canal police do.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 8,
    spoils: { oil: 25, supplies: 5 },
    leanings: ['haul', 'road'],
  },
  {
    id: 'pirate-mast',
    name: 'Pirate Radio',
    brief:
      'Pirate Aunty broadcasts from a mast on the Holm tenement. The Combine keeps knocking it down. Put it back up and she will read your name.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 16,
    spoils: { caps: 15, scrap: 10 },
    leanings: ['wire', 'climb'],
  },
  {
    id: 'friday-envelope',
    name: 'Friday Envelope',
    brief:
      'A patrol sergeant takes an envelope every Friday to look away on Glass Street. The usual runner got caught. Somebody has to hand it over smiling.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { caps: 20, supplies: 5 },
    leanings: ['con', 'stealth'],
  },
  {
    id: 'triage-night',
    name: 'Triage Night',
    brief:
      'A tenement fire on Pike Street, and the hospital takes nobody without papers. Set up in the laundry and sort who needs what first.',
    kind: 'standard',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 22,
    spoils: { supplies: 35 },
    leanings: ['medic', 'plan'],
  },
  {
    id: 'grey-coat',
    name: 'Grey Coat',
    brief:
      'Put on the grey coat, carry the clipboard, walk into the ration depot like the Combine sent you. Count the stock. Leave with a sample.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'further',
    durationMinutes: 20,
    spoils: { supplies: 20, caps: 10 },
    leanings: ['con', 'intel'],
  },
  {
    id: 'quay-arm-bench',
    name: 'Arm Tune',
    brief:
      'Half the dockers run on second-hand chrome arms that seize in the cold. Set up a bench on the quay and charge what the grease costs.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { caps: 15, scrap: 10 },
    leanings: ['chrome', 'repair'],
  },
  {
    id: 'ferry-hop',
    name: 'Ferry Hop',
    brief:
      'Three families want across the river to the free wards. The ferryman goes at midnight. The Combine river patrol goes whenever it likes.',
    kind: 'standard',
    grades: ['E-', 'E+'],
    travelBand: 'further',
    durationMinutes: 25,
    spoils: { caps: 20, supplies: 10 },
    leanings: ['escort', 'road'],
  },
  {
    id: 'pew-pull',
    name: 'Pew Pull',
    brief:
      'The chapel on Lower Vane burned out but the pews did not. Hardwood is hardwood. The priest says take them, God will not mind.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 6,
    spoils: { planks: 30 },
    leanings: ['haul', 'salvage'],
  },
  {
    id: 'doorway-duty',
    name: 'Doorway Duty',
    brief:
      'The corner shop on Keel Street gets robbed every payday. Stand in the doorway with your arms folded and they will pay you in stock.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { supplies: 20, caps: 5 },
    leanings: ['muscle'],
  },
  {
    id: 'word-with-lenny',
    name: 'A Word With Lenny',
    brief:
      'Lenny has been selling crew names to a Combine informant. Find where he drinks, then have a quiet word he will not forget.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 15,
    spoils: { caps: 15 },
    leanings: ['muscle', 'intel'],
  },
  {
    id: 'shutter-pop',
    name: 'Shutter Pop',
    brief:
      'The pharmacy on Lamb Street is shuttered and sealed by Combine order. The shutter lock is cheap. The shelves behind it are not.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { supplies: 25, caps: 5 },
    leanings: ['breach', 'stealth'],
  },
  {
    id: 'stairwell-clear',
    name: 'Stairwell Clear',
    brief:
      'A collapsed stairwell has cut off the top floors of Birch House. One small charge in the right place and the residents can come down for water.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { scrap: 15, caps: 10 },
    leanings: ['breach', 'salvage'],
  },
  {
    id: 'queue-jump',
    name: 'Queue Jump',
    brief:
      "The ration office lets in fifty a day. Get your crew's papers to the top of the list by Monday without anyone noticing the list moved.",
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { supplies: 25 },
    leanings: ['plan', 'con'],
  },
  {
    id: 'noodle-feud',
    name: 'Noodle Feud',
    brief:
      'Two noodle sellers on the same corner are one insult away from knives. Broker a line down the pavement that both of them can live with.',
    kind: 'standard',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { caps: 15, supplies: 5 },
    leanings: ['parley', 'talk'],
  },
  {
    id: 'hatch-street-truce',
    name: 'Gang Truce',
    brief:
      'The Rats and the Canal Boys both want Hatch Street. Get them in a room above the bakery and draw a line before somebody dies on it.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 18,
    spoils: { caps: 20, supplies: 10 },
    leanings: ['parley', 'intel'],
  },
  {
    id: 'walk-her-home',
    name: 'Walk Her Home',
    brief:
      "The nurse from the night clinic walks home through Butcher's Alley. After last week she wants company. She pays in bandages and advice.",
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 4,
    spoils: { supplies: 15, caps: 5 },
    leanings: ['escort', 'road'],
  },
  {
    id: 'wedding-party',
    name: 'Wedding Party',
    brief:
      'A wedding party has to cross gang turf to reach the registry office. Walk them there, keep the dress clean, and get a slice of cake.',
    kind: 'standard',
    grades: ['F', 'E'],
    travelBand: 'further',
    durationMinutes: 12,
    spoils: { caps: 15, supplies: 15 },
    leanings: ['escort', 'talk'],
  },
  {
    id: 'coal-barrow',
    name: 'Coal Barrow',
    brief:
      'A coal merchant with a bad back needs his barrow pushed round the Smithy estate before dark. Thirty stops, three flights each.',
    kind: 'standard',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 6,
    spoils: { oil: 15, caps: 8 },
    leanings: ['haul', 'road'],
  },
  {
    id: 'drone-crash',
    name: 'Drone Crash',
    brief:
      'A Combine delivery drone came down on the Marsh Flats. Reach it before the recovery van, which is slow, and the scavengers, who are not.',
    kind: 'standard',
    grades: ['E-', 'E+'],
    travelBand: 'further',
    durationMinutes: 20,
    spoils: { scrap: 20, highQualityMetal: 4, caps: 10 },
    leanings: ['salvage', 'road', 'repair'],
  },
  {
    id: 'camera-blind',
    name: 'Camera Blind',
    brief:
      'A new Combine camera went up over the market gate. Blind it without taking it down, so the feed looks fine and shows nothing at all.',
    kind: 'standard',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 15,
    spoils: { caps: 20 },
    leanings: ['wire', 'stealth'],
  },

  // Skirmishes.
  {
    id: 'pipe-gang',
    name: 'Pipe Gang',
    brief:
      'Four lads with lead pipes have been charging a toll on the Wick Street stairwell. Charge them back.',
    kind: 'battle',
    grades: ['F-', 'F'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { caps: 10, scrap: 10 },
    leanings: ['fight'],
  },
  {
    id: 'dead-bus-claim',
    name: 'Scrap Claim',
    brief:
      'Another scavenger crew says the dead bus on Orme Road is theirs. They have a chalk mark on it. You have more people.',
    kind: 'battle',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 6,
    spoils: { scrap: 25 },
    leanings: ['fight'],
  },
  {
    id: 'lost-patrol',
    name: 'Lost Patrol',
    brief:
      'A Combine foot patrol took a wrong turn into the old quarter and its radio is dead. They are frightened and armed, the worst kind.',
    kind: 'battle',
    grades: ['F+', 'E+'],
    travelBand: 'close',
    durationMinutes: 14,
    spoils: { caps: 15, supplies: 10, highQualityMetal: 3 },
    leanings: ['fight'],
  },
  {
    id: 'fish-market-brawl',
    name: 'Market Brawl',
    brief:
      'The fish sellers and the butchers have been at it since dawn. Break it up, keep the stalls standing, and send a bill to both.',
    kind: 'battle',
    grades: ['F-', 'F+'],
    travelBand: 'close',
    durationMinutes: 5,
    spoils: { supplies: 20, caps: 5 },
    leanings: ['fight'],
  },
  {
    id: 'flyover-kennels',
    name: 'Kennel Crew',
    brief:
      'A dog-fighting crew runs cages under the Tollgate flyover. Go in quiet, then go in loud. Let the dogs out first.',
    kind: 'battle',
    grades: ['F', 'E-'],
    travelBand: 'close',
    durationMinutes: 8,
    spoils: { caps: 15, supplies: 10 },
    leanings: ['fight'],
  },
  {
    id: 'magpie-roofs',
    name: 'Roof War',
    brief:
      'The Magpies have been raiding washing lines and water tanks from the rooftops. Meet them up there, on their ground, twelve floors up.',
    kind: 'battle',
    grades: ['F+', 'E'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { supplies: 20, caps: 5 },
    leanings: ['fight'],
  },
  {
    id: 'grating-ambush',
    name: 'Drain Ambush',
    brief:
      'Smugglers run crates through the Coldwater drains every Tuesday. Wait in the dark under the grating and let them come to you.',
    kind: 'battle',
    grades: ['F', 'E'],
    travelBand: 'close',
    durationMinutes: 10,
    spoils: { caps: 15, oil: 10 },
    leanings: ['fight'],
  },
  {
    id: 'pier-six-scrap',
    name: 'Quay Scrap',
    brief:
      "The dockers' union and a scab crew are settling it with boathooks on Pier Six. Pick a side, win it, then load the barge.",
    kind: 'battle',
    grades: ['E-', 'E+'],
    travelBand: 'further',
    durationMinutes: 15,
    spoils: { caps: 20, supplies: 15 },
    leanings: ['fight'],
  },
  {
    id: 'arcade-standoff',
    name: 'Arcade Standoff',
    brief:
      "The Glitch Kids have locked themselves in the arcade with a Combine officer's son. Nobody wants a funeral. Somebody has to go in.",
    kind: 'battle',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 18,
    spoils: { caps: 25 },
    leanings: ['fight'],
  },
  {
    id: 'tanner-row-collectors',
    name: 'Collector Crew',
    brief:
      "A loan shark's collectors are breaking fingers along Tanner Row. The residents clubbed together to hire someone who breaks back.",
    kind: 'battle',
    grades: ['F-', 'E-'],
    travelBand: 'close',
    durationMinutes: 8,
    spoils: { caps: 20 },
    leanings: ['fight'],
  },
  {
    id: 'tram-yard-feud',
    name: 'Yard Feud',
    brief:
      'Two crews want the copper in the Eastgate tram yard. Only one is leaving with it, and the rust will not care which.',
    kind: 'battle',
    grades: ['F+', 'E'],
    travelBand: 'further',
    durationMinutes: 12,
    spoils: { scrap: 25, caps: 5 },
    leanings: ['fight'],
  },
  {
    id: 'chrome-boys',
    name: 'Chrome Boys',
    brief:
      'A gang of lads with cheap chrome arms has been punching holes in shop shutters. Their fittings are shoddy. Aim for the joints.',
    kind: 'battle',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 16,
    spoils: { scrap: 15, caps: 15 },
    leanings: ['fight'],
  },
  {
    id: 'bread-barrow-jump',
    name: 'Barrow Jump',
    brief:
      'Somebody keeps jumping the bread barrows on the way up from the bakery. Walk beside one tonight and wait for the jump.',
    kind: 'battle',
    grades: ['F-', 'F'],
    travelBand: 'close',
    durationMinutes: 4,
    spoils: { supplies: 20 },
    leanings: ['fight'],
  },
  {
    id: 'carver-square-riot',
    name: 'Riot Corner',
    brief:
      'A food riot on Carver Square is going the wrong way. Hold the corner by the clinic so the injured can get through the door.',
    kind: 'battle',
    grades: ['E', 'E+'],
    travelBand: 'close',
    durationMinutes: 20,
    spoils: { supplies: 25, caps: 5 },
    leanings: ['fight'],
  },
  {
    id: 'squat-barricade',
    name: 'Squat Barricade',
    brief:
      'Combine bailiffs hired a street gang to clear the Corder squat. Barricade the stairwell and make it cost them more than it pays.',
    kind: 'battle',
    grades: ['F+', 'E'],
    travelBand: 'close',
    durationMinutes: 12,
    spoils: { planks: 15, supplies: 10 },
    leanings: ['fight'],
  },
  {
    id: 'holloway-switchboard',
    name: 'Switchboard Scuffle',
    brief:
      'A crew is cutting power to the Holloway blocks and selling it back by the hour. Their switchboard is in the substation. So are they.',
    kind: 'battle',
    grades: ['E-', 'E+'],
    travelBand: 'close',
    durationMinutes: 16,
    spoils: { caps: 15, scrap: 10 },
    leanings: ['fight'],
  },
];
