import type { MissionTemplate } from '../missions.js';

/** The stronghold band, B- to A+: Combine vaults, labs, towers and the walls around them. */
export const STRONGHOLD_JOBS: readonly MissionTemplate[] = [
  {
    id: 'vault-of-deeds',
    name: 'Vault of Deeds',
    brief:
      'Every title in the lower city sits in one Combine vault under the land registry. Open it, copy it, and let the owners find out who they are.',
    kind: 'standard',
    grades: ['B-', 'A-'],
    travelBand: 'furthest',
    durationMinutes: 240,
    spoils: { caps: 50, highQualityMetal: 8 },
    leanings: ['con', 'wire', 'plan'],
  },
  {
    id: 'sky-rail-skim',
    name: 'Sky Rail Skim',
    brief:
      'The sky-rail fare boxes are emptied at the terminus at midnight. Ride the last car in a borrowed uniform and step off before the count.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 150,
    spoils: { caps: 60, scrap: 10 },
    leanings: ['con', 'stealth', 'road'],
  },
  {
    id: 'reactor-coolant-lift',
    name: 'Coolant Lift',
    brief:
      'Reactor Hall Four is throwing away coolant that still works. Get it out in drums before the Combine notices it was worth keeping.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 180,
    spoils: { oil: 40, highQualityMetal: 6 },
    leanings: ['haul', 'repair'],
  },
  {
    id: 'prison-barge-visit',
    name: 'Barge Visitation',
    brief:
      'A man on the prison barge knows where the Combine buried the old payroll. Get aboard on a visitor pass and come back with the number.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 150,
    spoils: { caps: 40, supplies: 20 },
    leanings: ['con', 'talk', 'intel'],
  },
  {
    id: 'broadcast-dead-air',
    name: 'Dead Air',
    brief:
      'The broadcast tower plays the curfew anthem at six. Hold the relay room for four minutes and play the city something else instead.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 210,
    spoils: { caps: 30, scrap: 20, highQualityMetal: 6 },
    leanings: ['wire', 'climb', 'plan'],
  },
  {
    id: 'tier-nine-audit',
    name: 'Floor Audit',
    brief:
      'The bank floor on Tier Nine is being audited by men who do not exist. Be those men, carry the ledgers out, and sign for them.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 300,
    spoils: { caps: 80, highQualityMetal: 5 },
    leanings: ['con', 'plan', 'intel'],
  },
  {
    id: 'water-plant-valve',
    name: 'Valve Ninety',
    brief:
      'The upper tiers drink first because one valve in the water plant says so. Turn it the other way and keep the engineers off it.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { supplies: 40, scrap: 10 },
    leanings: ['repair', 'muscle'],
  },
  {
    id: 'lab-cold-chain',
    name: 'Cold Chain',
    brief:
      'A Combine research lab ships tissue samples at minus eighty. Lift the cooler, keep it cold, and deliver it to a clinic that asked nicely.',
    kind: 'standard',
    grades: ['B-', 'A-'],
    travelBand: 'furthest',
    durationMinutes: 180,
    spoils: { supplies: 50, caps: 20 },
    leanings: ['medic', 'escort', 'road'],
  },
  {
    id: 'meridian-window-cleaners',
    name: 'Window Cleaners',
    brief:
      'Nobody checks the window cleaners on the Meridian tower. Go up the outside, open the forty-second floor, and take what the board left out.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 240,
    spoils: { caps: 60, highQualityMetal: 10 },
    leanings: ['climb', 'stealth'],
  },
  {
    id: 'kessler-substation-swap',
    name: 'Substation Swap',
    brief:
      'Rewire the Kessler substation so the upper tier pays for the lower district lights. Nobody up there reads a meter anyway.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'close',
    durationMinutes: 160,
    spoils: { caps: 30, scrap: 25 },
    leanings: ['wire', 'repair'],
  },
  {
    id: 'chemist-notebooks',
    name: 'Lab Notebooks',
    brief:
      'A Combine chemist keeps her real results on paper. Find the notebooks in her lab, photograph every page, and put them back in order.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 220,
    spoils: { caps: 40, supplies: 15, oil: 10 },
    leanings: ['intel', 'stealth'],
  },
  {
    id: 'implant-recall',
    name: 'Implant Recall',
    brief:
      'The Combine is recalling a batch of cheap arm implants by removing them. Reach the clinic first and get the patients out with their arms.',
    kind: 'standard',
    grades: ['B-', 'A-'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { supplies: 30, highQualityMetal: 12 },
    leanings: ['chrome', 'medic', 'escort'],
  },
  {
    id: 'dunmore-points-failure',
    name: 'Points Failure',
    brief:
      'Switch the points at the Dunmore junction and an armoured alloy train rolls into your siding. Switch them back before dawn.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 320,
    spoils: { highQualityMetal: 20, scrap: 30 },
    leanings: ['plan', 'repair', 'haul'],
  },
  {
    id: 'arrears-court-docket',
    name: 'Arrears Court',
    brief:
      'The arrears court sits on Thursdays and sentences by the hundred. Get the docket, lose forty names from it, and leave the clerk smiling.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'close',
    durationMinutes: 140,
    spoils: { caps: 50, supplies: 10 },
    leanings: ['con', 'talk'],
  },
  {
    id: 'lantern-mooring-mast',
    name: 'Mooring Mast',
    brief:
      'A Combine supply dirigible ties up at the Lantern mast overnight. Climb the mast, cut the cargo net, and have a crew waiting underneath.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 260,
    spoils: { supplies: 40, planks: 20, oil: 15 },
    leanings: ['climb', 'haul'],
  },
  {
    id: 'turbine-hall-strip',
    name: 'Turbine Hall',
    brief:
      'The old turbine hall is due for demolition on Monday. Strip the bearings and the copper before the Combine sells the lot for scrap.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 240,
    spoils: { scrap: 40, highQualityMetal: 12 },
    leanings: ['salvage', 'haul', 'repair'],
  },
  {
    id: 'board-member-defection',
    name: 'Board Member',
    brief:
      'A junior board member wants out of the Combine and brings the codes with him. Get him down forty floors and past his own security.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 420,
    spoils: { caps: 70, highQualityMetal: 10 },
    leanings: ['escort', 'climb', 'plan'],
  },
  {
    id: 'security-firm-ceasefire',
    name: 'Ceasefire Table',
    brief:
      'Two Combine security firms are about to shoot each other over one depot. Sit between them, cool it down, and invoice both for the favour.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'further',
    durationMinutes: 280,
    spoils: { caps: 90 },
    leanings: ['parley', 'talk'],
  },
  {
    id: 'market-riot-insurance',
    name: 'Riot Insurance',
    brief:
      'The Combine insures the tier markets against riot. Stage a small one with paid actors, file the claim, and split the payout.',
    kind: 'standard',
    grades: ['B-', 'A-'],
    travelBand: 'close',
    durationMinutes: 180,
    spoils: { caps: 70, supplies: 10 },
    leanings: ['con', 'plan', 'muscle'],
  },
  {
    id: 'canal-fibre-tap',
    name: 'Canal Fibre',
    brief:
      'Splice into the sealed Combine fibre that runs under the canal. Every order to the garrison goes through it, and soon through you.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 260,
    spoils: { caps: 40, scrap: 15, highQualityMetal: 8 },
    leanings: ['wire', 'stealth', 'intel'],
  },
  {
    id: 'upper-pharmacy-bins',
    name: 'Pharmacy Bins',
    brief:
      'The upper-tier pharmacy bins anything a day past its date. Get the lot down to the lower wards before the incinerator starts.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 130,
    spoils: { supplies: 60 },
    leanings: ['medic', 'haul', 'road'],
  },
  {
    id: 'seed-vault-harvest',
    name: 'Seed Vault',
    brief:
      'The Combine seed vault holds every crop the lower city was told had died out. Walk in with a cold box and walk out with a harvest.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 400,
    spoils: { supplies: 70, planks: 15 },
    leanings: ['stealth', 'intel', 'haul'],
  },
  {
    id: 'levy-barge-lock',
    name: 'Levy Barge',
    brief:
      "The levy barge comes downriver on Fridays heavy with the week's taxes. Stop it at the lock and persuade the crew it sank.",
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'furthest',
    durationMinutes: 240,
    spoils: { caps: 80, oil: 10 },
    leanings: ['muscle', 'talk', 'road'],
  },
  {
    id: 'chip-foundry-clean-room',
    name: 'Clean Room',
    brief:
      'The chip foundry runs a clean room nobody has breathed in for a year. Suit up, walk the line, and pocket the finished wafers.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 380,
    spoils: { highQualityMetal: 25, caps: 30 },
    leanings: ['chrome', 'stealth', 'wire'],
  },
  {
    id: 'upper-transit-passes',
    name: 'Transit Passes',
    brief:
      'Print a hundred upper-tier transit passes good enough to fool a scanner. The ink is Combine issue, so you steal that first.',
    kind: 'standard',
    grades: ['B-', 'B+'],
    travelBand: 'close',
    durationMinutes: 180,
    spoils: { caps: 55, supplies: 10 },
    leanings: ['con', 'wire'],
  },
  {
    id: 'pellam-maglev-wreck',
    name: 'Pellam Cut',
    brief:
      'A mag-lev car came off the track at Pellam Cut and the Combine fenced the wreck off. The magnets alone are worth the walk.',
    kind: 'standard',
    grades: ['B-', 'A-'],
    travelBand: 'furthest',
    durationMinutes: 240,
    spoils: { highQualityMetal: 20, scrap: 40 },
    leanings: ['salvage', 'road'],
  },
  {
    id: 'halden-safety-board',
    name: 'Safety Board',
    brief:
      'Pose as the safety board at the Halden reactor. Inspect everything, condemn half of it, and take the condemned parts away with you.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'further',
    durationMinutes: 300,
    spoils: { highQualityMetal: 15, oil: 20, scrap: 20 },
    leanings: ['con', 'repair', 'salvage'],
  },
  {
    id: 'bridge-prisoner-swap',
    name: 'Bridge Swap',
    brief:
      'The Combine holds three of ours and we hold one of theirs. Run the swap on the Varick bridge and make sure nobody gets clever.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { caps: 40, supplies: 30 },
    leanings: ['parley', 'escort'],
  },
  {
    id: 'garrison-uplink-dish',
    name: 'Uplink Dish',
    brief:
      'The dish on the Spire relay talks to every garrison in the city. Climb it in the wind and point it at the sea for an hour.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'further',
    durationMinutes: 360,
    spoils: { caps: 30, highQualityMetal: 15, scrap: 15 },
    leanings: ['climb', 'wire'],
  },
  {
    id: 'hospital-sealed-wing',
    name: 'Sealed Wing',
    brief:
      'The Combine hospital has a wing that is on no floor plan. Find out who they keep in it and bring back the files, or the patients.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'further',
    durationMinutes: 300,
    spoils: { supplies: 45, caps: 25 },
    leanings: ['intel', 'medic', 'stealth'],
  },
  {
    id: 'boardroom-listening-wire',
    name: 'Boardroom Bug',
    brief:
      'Plant a listening wire in the boardroom on Tier Twelve. The cleaners go in at four in the morning and one of them owes you.',
    kind: 'standard',
    grades: ['B-', 'A-'],
    travelBand: 'further',
    durationMinutes: 160,
    spoils: { caps: 45, scrap: 10 },
    leanings: ['wire', 'con'],
  },
  {
    id: 'night-deposit-cage',
    name: 'Night Deposit',
    brief:
      'The Combine bank takes night deposits down a chute that ends in a cage. Get into the cage from below and wait for it to fill.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 450,
    spoils: { caps: 100 },
    leanings: ['breach', 'plan', 'stealth'],
  },
  {
    id: 'governor-moat-drain',
    name: 'Drain the Moat',
    brief:
      "The Governor's compound has a moat for show and a pump house for real. Drain it overnight and see what they have dropped in.",
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'furthest',
    durationMinutes: 270,
    spoils: { scrap: 30, highQualityMetal: 10, caps: 20 },
    leanings: ['repair', 'salvage'],
  },
  {
    id: 'census-engine-rewrite',
    name: 'Counting Engine',
    brief:
      'The Combine sorts every citizen through one counting engine. Teach it that the lower district has twice as many children to feed.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'further',
    durationMinutes: 320,
    spoils: { supplies: 60, caps: 20 },
    leanings: ['wire', 'intel'],
  },
  {
    id: 'upper-freight-lift',
    name: 'Freight Lift',
    brief:
      'The freight lift to the upper tier carries alloy up and nothing down. Ride it up, swap the manifests, and ride it down full.',
    kind: 'standard',
    grades: ['B-', 'A'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { highQualityMetal: 18, scrap: 20 },
    leanings: ['haul', 'con', 'climb'],
  },
  {
    id: 'evidence-store-surgeon',
    name: 'Struck-Off Surgeon',
    brief:
      'A struck-off Combine surgeon will fit your people with military chrome, once you get her kit out of the garrison evidence store.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'further',
    durationMinutes: 400,
    spoils: { highQualityMetal: 20, supplies: 25 },
    leanings: ['chrome', 'breach'],
  },
  {
    id: 'grid-blackout-window',
    name: 'Blackout Window',
    brief:
      'The city grid goes dark for ninety seconds during the Combine switchover. Fit three jobs into that window and finish all of them.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'close',
    durationMinutes: 300,
    spoils: { caps: 50, highQualityMetal: 12, oil: 15 },
    leanings: ['plan', 'wire'],
  },
  {
    id: 'varick-toll-schedule',
    name: 'Toll Schedule',
    brief:
      'The Varick bridge toll is moved in cash every six hours. Learn the schedule better than the drivers do, then be early once.',
    kind: 'standard',
    grades: ['B-', 'A'],
    travelBand: 'further',
    durationMinutes: 180,
    spoils: { caps: 75, oil: 10 },
    leanings: ['intel', 'road'],
  },
  {
    id: 'dockside-weigh-station',
    name: 'Weigh Station',
    brief:
      'The weigh station at the Combine docks fines every hull by the tonne. Run the scales for a week and let the fines go the other way.',
    kind: 'standard',
    grades: ['B', 'A'],
    travelBand: 'further',
    durationMinutes: 300,
    spoils: { caps: 45, oil: 20, planks: 15 },
    leanings: ['talk', 'repair'],
  },
  {
    id: 'solstice-roof-garden',
    name: 'Solstice Garden',
    brief:
      "The Combine board throws a party in the roof garden every solstice. Get on the guest list and leave with the host's safe keys.",
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 360,
    spoils: { caps: 85, highQualityMetal: 6 },
    leanings: ['con', 'talk', 'climb'],
  },
  {
    id: 'harbour-patrol-hull',
    name: 'Harbour Mud',
    brief:
      'Cut a scuttled Combine patrol boat out of the harbour mud. The armour plate comes up in slabs if the divers keep their nerve.',
    kind: 'standard',
    grades: ['B-', 'A'],
    travelBand: 'further',
    durationMinutes: 280,
    spoils: { highQualityMetal: 25, scrap: 30 },
    leanings: ['salvage', 'breach', 'haul'],
  },
  {
    id: 'mine-labour-lottery',
    name: 'Labour Lottery',
    brief:
      'The Combine labour exchange sends crews to the mines by lottery. Rig the draw so the mine gets its own foremen for a change.',
    kind: 'standard',
    grades: ['B-', 'A'],
    travelBand: 'close',
    durationMinutes: 150,
    spoils: { caps: 40, supplies: 30 },
    leanings: ['muscle', 'con'],
  },
  {
    id: 'barracks-fever',
    name: 'Barracks Fever',
    brief:
      'Fever is running through a Combine barracks and the officers are keeping it quiet. Get in with the vaccine and out with a debt owed.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'further',
    durationMinutes: 260,
    spoils: { supplies: 40, caps: 40 },
    leanings: ['medic', 'talk', 'parley'],
  },
  {
    id: 'offshore-turbine-crown',
    name: 'Turbine Crown',
    brief:
      'The offshore turbines feed the upper tier and nobody else. Climb a crown in a gale, fit the shunt, and send a slice of it ashore.',
    kind: 'standard',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 480,
    spoils: { oil: 40, highQualityMetal: 10 },
    leanings: ['climb', 'repair', 'road'],
  },
  {
    id: 'garrison-ration-contract',
    name: 'Mess Contract',
    brief:
      'The garrison buys its rations from whoever the quartermaster likes. Make him like you, then deliver half and bill for the lot.',
    kind: 'standard',
    grades: ['B-', 'A'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { supplies: 50, caps: 30 },
    leanings: ['talk', 'parley', 'haul'],
  },
  {
    id: 'spire-chrome-audit',
    name: 'Chrome Registry',
    brief:
      'Every implant in the city carries a Combine serial. Break into the registry and the upper tier stops knowing whose arm is whose.',
    kind: 'standard',
    grades: ['B+', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 340,
    spoils: { caps: 40, highQualityMetal: 15 },
    leanings: ['chrome', 'wire', 'intel'],
  },

  // Sieges.
  {
    id: 'tier-six-gate',
    name: 'Tier Six Gate',
    brief:
      'Take the gate on the Tier Six wall and hold it while three crews get through. The snipers on the parapet have seen this before.',
    kind: 'battle',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 180,
    spoils: { caps: 40, scrap: 30 },
    leanings: ['fight'],
  },
  {
    id: 'armoured-depot-siege',
    name: 'Armoured Depot',
    brief:
      'The Combine keeps its spare armour in a depot with walls a metre thick. Blow the side door and hold the yard while the lorries load.',
    kind: 'battle',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 220,
    spoils: { highQualityMetal: 20, scrap: 30 },
    leanings: ['fight'],
  },
  {
    id: 'halvorsen-compound',
    name: 'Halvorsen Labs',
    brief:
      'Storm the Halvorsen research compound and sit on the labs until the data is off the servers. The breakers on the wall do not surrender.',
    kind: 'battle',
    grades: ['B', 'A-'],
    travelBand: 'furthest',
    durationMinutes: 260,
    spoils: { caps: 40, highQualityMetal: 15, supplies: 15 },
    leanings: ['fight'],
  },
  {
    id: 'reactor-hall-two',
    name: 'Reactor Hall Two',
    brief:
      'Take Reactor Hall Two and hold the control room against a garrison that knows every corridor. Do not touch the red panel.',
    kind: 'battle',
    grades: ['B+', 'A'],
    travelBand: 'further',
    durationMinutes: 320,
    spoils: { oil: 40, highQualityMetal: 15 },
    leanings: ['fight'],
  },
  {
    id: 'prison-barge-storm',
    name: 'Barge Storm',
    brief:
      'Board the prison barge at anchor and hold the deck while the cells are opened. The guards in the tower have rifles and all night.',
    kind: 'battle',
    grades: ['B-', 'B+'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { supplies: 40, caps: 30 },
    leanings: ['fight'],
  },
  {
    id: 'filter-house-siege',
    name: 'Filter House',
    brief:
      'The Combine walled the water plant after last summer. Break the perimeter and hold the filter house until the valves are ours.',
    kind: 'battle',
    grades: ['B', 'A-'],
    travelBand: 'further',
    durationMinutes: 240,
    spoils: { supplies: 50, scrap: 20 },
    leanings: ['fight'],
  },
  {
    id: 'crown-street-station',
    name: 'Crown Street',
    brief:
      'Seize the Crown Street sky-rail station, sandbag both platforms, and hold them while the armoured car is emptied onto your carts.',
    kind: 'battle',
    grades: ['B-', 'A-'],
    travelBand: 'further',
    durationMinutes: 200,
    spoils: { caps: 60, highQualityMetal: 10 },
    leanings: ['fight'],
  },
  {
    id: 'broadcast-keep',
    name: 'Broadcast Keep',
    brief:
      'The broadcast tower has a fortified base and a garrison on every landing. Fight up twelve floors and hold the studio for the speech.',
    kind: 'battle',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 420,
    spoils: { caps: 50, scrap: 20, highQualityMetal: 12 },
    leanings: ['fight'],
  },
  {
    id: 'bank-shutter-siege',
    name: 'Bank Shutter',
    brief:
      'The Tier Nine bank has a steel shutter, a sniper nest and a vault on a timer. Hold the floor until the timer runs out, then carry.',
    kind: 'battle',
    grades: ['B+', 'A'],
    travelBand: 'furthest',
    durationMinutes: 300,
    spoils: { caps: 90, highQualityMetal: 8 },
    leanings: ['fight'],
  },
  {
    id: 'governors-wall',
    name: "Governor's Wall",
    brief:
      "The Governor's compound wall has stood for ten years. Tonight it has breakers on it and you have charges. See which lasts.",
    kind: 'battle',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 480,
    spoils: { caps: 60, highQualityMetal: 20 },
    leanings: ['fight'],
  },
  {
    id: 'barracks-lockdown',
    name: 'Barracks Lockdown',
    brief:
      'Pin a Combine garrison inside its own barracks while the lower district moves house. Nobody comes out of those gates until dawn.',
    kind: 'battle',
    grades: ['B', 'A-'],
    travelBand: 'close',
    durationMinutes: 280,
    spoils: { supplies: 40, planks: 20, caps: 20 },
    leanings: ['fight'],
  },
  {
    id: 'alloy-keep',
    name: 'Alloy Keep',
    brief:
      'The alloy reserve sits in a keep built for exactly this night. Breach the gate, hold the courtyard, and fill every cart you brought.',
    kind: 'battle',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 500,
    spoils: { highQualityMetal: 30, scrap: 20 },
    leanings: ['fight'],
  },
  {
    id: 'airstrip-hangars',
    name: 'Airstrip Hangars',
    brief:
      'Take the Combine airstrip and hold the hangars against the counterattack. Nobody can fly anything out, so drain the fuel instead.',
    kind: 'battle',
    grades: ['B+', 'A'],
    travelBand: 'furthest',
    durationMinutes: 340,
    spoils: { oil: 60, scrap: 20 },
    leanings: ['fight'],
  },
  {
    id: 'iron-gate',
    name: 'The Iron Gate',
    brief:
      'The Iron Gate is where the lower city ends. Take it, hold it for one night, and let everyone watching see it can be done.',
    kind: 'battle',
    grades: ['A', 'A+'],
    travelBand: 'further',
    durationMinutes: 600,
    spoils: { caps: 60, highQualityMetal: 15, supplies: 20 },
    leanings: ['fight'],
  },
  {
    id: 'walled-hospital',
    name: 'Walled Hospital',
    brief:
      'The garrison has walled up the only hospital in the district. Break in, hold the wards, and keep the doctors working through it.',
    kind: 'battle',
    grades: ['B-', 'B+'],
    travelBand: 'close',
    durationMinutes: 180,
    spoils: { supplies: 60, caps: 15 },
    leanings: ['fight'],
  },
  {
    id: 'implant-works-assault',
    name: 'Implant Works',
    brief:
      'The implant works trains its guards on the product. Hit the walls expecting men who cannot feel pain, and take the stock.',
    kind: 'battle',
    grades: ['B+', 'A'],
    travelBand: 'further',
    durationMinutes: 300,
    spoils: { highQualityMetal: 25, caps: 30 },
    leanings: ['fight'],
  },
  {
    id: 'hill-jammer-fort',
    name: 'Jammer Fort',
    brief:
      'Storm the hill fort that jams every radio in the district. Hold the mast long enough to switch it off, then make it stay off.',
    kind: 'battle',
    grades: ['A-', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 440,
    spoils: { scrap: 30, highQualityMetal: 15 },
    leanings: ['fight'],
  },
  {
    id: 'maglev-depot-dark',
    name: 'Mag-Lev Sheds',
    brief:
      'The mag-lev depot sits behind blast walls and floodlights. Cut the power, go in dark, and hold the sheds until the sun comes up.',
    kind: 'battle',
    grades: ['B-', 'A-'],
    travelBand: 'further',
    durationMinutes: 240,
    spoils: { highQualityMetal: 20, scrap: 25, oil: 10 },
    leanings: ['fight'],
  },
  {
    id: 'upper-tier-stair',
    name: 'The Long Stair',
    brief:
      'One staircase climbs to the upper tier with a garrison at the top. Take it a landing at a time and keep every landing you take.',
    kind: 'battle',
    grades: ['A', 'A+'],
    travelBand: 'furthest',
    durationMinutes: 640,
    spoils: { caps: 50, highQualityMetal: 20 },
    leanings: ['fight'],
  },
  {
    id: 'scrip-mint-siege',
    name: 'Siege of the Mint',
    brief:
      'The Combine mint prints scrip behind three walls and a moat. Take the first two tonight. The third wall is a conversation.',
    kind: 'battle',
    grades: ['B+', 'A'],
    travelBand: 'furthest',
    durationMinutes: 360,
    spoils: { caps: 100 },
    leanings: ['fight'],
  },
];
