import { z } from 'zod';
import { IdSchema, IsoDateTimeSchema } from '../primitives.js';

/**
 * Notifications: the game telling you something happened while you were not looking.
 *
 * Modelled on what Grepolis and its neighbours actually do, because the shape is well understood
 * and players arrive already knowing it: a bell with an unread count, a list newest first, a row
 * that marks itself read when you open it, a way to mark everything read, and a settings page that
 * decides which kinds reach you at all.
 *
 * ## A notification is a receipt, not a message
 *
 * Every one of these is generated by the game about something that already happened, and every one
 * carries a **link to the thing it is about**. A notification with nowhere to go is a line of text
 * that makes a player hunt, which is the failure mode of every half-built notification system.
 *
 * ## Kinds are the unit of filtering
 *
 * The settings page is a switch per {@link NotificationKind}, and the *emitter* checks it rather
 * than the reader: a notification a player has switched off is never written. That is the choice
 * with consequences, so it is worth naming. Filtering on read would let somebody turn a category
 * back on and find three weeks of history waiting; filtering on write means the switch is about
 * the future, which is how a player reads it. The unread badge is therefore always a count of
 * things they asked for.
 *
 * ## Groups
 *
 * The settings screen groups the kinds, because thirteen switches in one column is a wall. The
 * groups have no mechanical meaning beyond that.
 */

export const NOTIFICATION_GROUPS = ['military', 'district', 'crew', 'social'] as const;
export const NotificationGroupSchema = z.enum(NOTIFICATION_GROUPS);
export type NotificationGroup = z.infer<typeof NotificationGroupSchema>;

export const NOTIFICATION_GROUP_LABELS: Record<NotificationGroup, string> = {
  military: 'Fighting',
  district: 'The district',
  crew: 'The crew',
  social: 'People',
};

export const NOTIFICATION_KINDS = [
  // Military
  'battle_report',
  'battle_incoming',
  'reinforcement_arrived',
  'mission_home',
  // The district
  'building_done',
  'research_done',
  'training_done',
  'unit_trained',
  'district_attacked',
  // The crew
  'officer_hired',
  'payroll_due',
  // People
  'message_received',
  'faction_invite',
  'faction_joined',
  'faction_left',
] as const;
export const NotificationKindSchema = z.enum(NOTIFICATION_KINDS);
export type NotificationKind = z.infer<typeof NotificationKindSchema>;

export interface NotificationKindSpec {
  group: NotificationGroup;
  /** The switch's label on the settings page. */
  label: string;
  /** One line under it, saying what turning it off would stop. */
  blurb: string;
  /** The icon the row carries in the list. */
  icon: string;
  /**
   * Whether a player can switch it off.
   *
   * Two cannot: a battle report and an attack coming at your district. Those are the game telling
   * you that something irreversible has happened or is about to, and a game that lets you silence
   * that is a game that loses your army while you are reading the market.
   */
  alwaysOn?: boolean;
}

export const NOTIFICATION_KIND_SPECS: Readonly<Record<NotificationKind, NotificationKindSpec>> = {
  battle_report: {
    group: 'military',
    label: 'Battle reports',
    blurb: 'How a fight you were in actually went.',
    icon: 'battles',
    alwaysOn: true,
  },
  district_attacked: {
    group: 'district',
    label: 'Attacks on your district',
    blurb: 'Somebody has called a fight on ground you hold.',
    icon: 'shield',
    alwaysOn: true,
  },
  battle_incoming: {
    group: 'military',
    label: 'Fights you have called',
    blurb: 'A mark you set is about to come up.',
    icon: 'battles',
  },
  reinforcement_arrived: {
    group: 'military',
    label: 'Reinforcements',
    blurb: 'An ally has put units into a fight of yours, or you into one of theirs.',
    icon: 'crew',
  },
  mission_home: {
    group: 'military',
    label: 'Crews coming home',
    blurb: 'A job is finished and the crew is back.',
    icon: 'missions',
  },
  building_done: {
    group: 'district',
    label: 'Building work',
    blurb: 'A structure has finished going up.',
    icon: 'district',
  },
  research_done: {
    group: 'district',
    label: 'The Lab',
    blurb: 'An investigation, a programme or a modification has landed.',
    icon: 'research',
  },
  training_done: {
    group: 'crew',
    label: 'Training',
    blurb: 'Somebody has finished an hour on the floor.',
    icon: 'training',
  },
  unit_trained: {
    group: 'district',
    label: 'Units off the bench',
    blurb: 'A batch has finished training.',
    icon: 'units',
  },
  officer_hired: {
    group: 'crew',
    label: 'Hiring',
    blurb: 'Somebody has signed, or walked.',
    icon: 'bar',
  },
  payroll_due: {
    group: 'crew',
    label: 'Payroll',
    blurb: 'The weekly wage bill has come out of the stockpile.',
    icon: 'caps',
  },
  message_received: {
    group: 'social',
    label: 'Messages',
    blurb: 'Somebody has written to you.',
    icon: 'messages',
  },
  faction_invite: {
    group: 'social',
    label: 'Faction invitations',
    blurb: 'A faction has asked you to join them.',
    icon: 'faction',
  },
  faction_joined: {
    group: 'social',
    label: 'People joining',
    blurb: 'Somebody new has come to your faction.',
    icon: 'faction',
  },
  faction_left: {
    group: 'social',
    label: 'People leaving',
    blurb: 'Somebody has left your faction, or been shown the door.',
    icon: 'faction',
  },
};

/** The kinds a player is never allowed to silence. */
export const ALWAYS_ON_KINDS: readonly NotificationKind[] = NOTIFICATION_KINDS.filter(
  (kind) => NOTIFICATION_KIND_SPECS[kind].alwaysOn === true,
);

export function isAlwaysOn(kind: NotificationKind): boolean {
  return NOTIFICATION_KIND_SPECS[kind].alwaysOn === true;
}

export const NotificationSchema = z.object({
  id: IdSchema,
  kind: NotificationKindSchema,
  /** The headline, already written by the emitter: a notification is never assembled on the client. */
  title: z.string().min(1),
  /** One line under it. May be empty where the title says the whole thing. */
  body: z.string(),
  /**
   * Where this goes when clicked, as an in-app route.
   *
   * Not optional in practice and not optional in spirit: a receipt you cannot follow back to the
   * thing it is about is the failure mode this whole feature exists to avoid.
   */
  link: z.string().min(1),
  createdAt: IsoDateTimeSchema,
  readAt: IsoDateTimeSchema.nullable(),
});
export type Notification = z.infer<typeof NotificationSchema>;

/**
 * Which kinds this player wants.
 *
 * Stored sparsely: only the kinds explicitly switched **off** are recorded, so a kind added to the
 * catalogue tomorrow is on by default for everybody who has ever touched the settings page. The
 * other way round (record what is on) silently opts every existing player out of every new kind,
 * which reads as a broken feature rather than as a default.
 */
export const NotificationSettingsSchema = z.object({
  muted: z.array(NotificationKindSchema).default([]),
});
export type NotificationSettings = z.infer<typeof NotificationSettingsSchema>;

export function defaultNotificationSettings(): NotificationSettings {
  return { muted: [] };
}

/** Whether a notification of this kind should be written at all for this player. */
export function wantsNotification(settings: NotificationSettings, kind: NotificationKind): boolean {
  return isAlwaysOn(kind) || !settings.muted.includes(kind);
}

/** The settings with one kind flipped. An always-on kind cannot be muted, whatever is asked. */
export function withMuted(
  settings: NotificationSettings,
  kind: NotificationKind,
  muted: boolean,
): NotificationSettings {
  if (isAlwaysOn(kind)) return settings;
  const without = settings.muted.filter((entry) => entry !== kind);
  return { muted: muted ? [...without, kind] : without };
}

export function unreadCount(notifications: readonly Notification[]): number {
  return notifications.filter((entry) => entry.readAt === null).length;
}

/**
 * How a count is drawn on a badge.
 *
 * Capped, because a three-digit number does not fit in a dot beside an icon and a player who has
 * 340 unread is not making a decision on the exact figure.
 */
export const BADGE_MAX = 99;
export function badgeCount(count: number): string {
  return count > BADGE_MAX ? `${BADGE_MAX}+` : String(count);
}
