/**
 * Asking for a domain object's art: the view-facing half of the ADR 0001 §5.1 seam.
 *
 * A view names a *thing* (this overseer, this district), never a file. It gets pixels back only
 * when a delivery file for that thing exists in `assets/`; otherwise it gets `null` and paints its
 * own interim look. Dropping `portrait-overseer-01.webp` into `assets/` flips the portrait from
 * gradient to painted with no TypeScript edit.
 *
 * One function, and it hands back a **URL**. There was a second that handed back a Pixi `Texture`,
 * for a rendering layer nothing ever mounted; it went with that layer on 2026-09-24.
 *
 * Plates and planes do not come through here by *key*: their art is an `AssetKey` rather than a
 * domain id needing resolution. Grepping this module finds every *domain-addressed* consumer of
 * delivered art, not every consumer.
 */
import {
  DEFAULT_CITY_ID,
  tryResolveAssetKey,
  type AssetRef,
  type BuildingKind,
} from '@frontline/shared';
import { artLoader, type ArtLoader } from './loader';
import { DELIVERED_ART } from './source';

/** For DOM views: the delivered file's URL, or `null` while the key still paints procedurally. */
export function deliveredUrl(ref: AssetRef, loader: ArtLoader = artLoader): string | null {
  const key = tryResolveAssetKey(ref);
  const source = key === undefined ? undefined : loader.sourceOf(key);
  return source?.kind === 'file' ? source.url : null;
}

/**
 * A structure's picture, cut out of the district painting itself.
 *
 * Generated by `scripts/building-portraits.ts` from the same traced outline the map hit-tests, so
 * the window's illustration is *the building the player clicked* rather than a separate drawing of
 * something with the same name. The `building-<kind>` masters were exactly that: separate drawings:
 * made for the previous plate, and against the delivered painting they read as the wrong
 * building, which is what they were reported as.
 *
 * Not routed through the manifest on purpose. These are **derived** from a delivered asset rather
 * than delivered themselves: there is nothing for the maintainer to draw and nothing to order, and a
 * manifest entry would put twelve rows on the art order sheet asking for work that already exists.
 */
export function buildingPortraitUrl(kind: BuildingKind): string | null {
  return DELIVERED_ART.get(`portrait-${kind}.webp`) ?? null;
}

/**
 * A city's painting on the world screen, pending a manifest entry for it.
 *
 * Named off the city id, so dropping `city-ashfall.webp` (and `city-reliquary.webp`, and so on for
 * the five in `CITIES`) into `assets/` puts the painting on the card with no TypeScript edit.
 * Until one lands, `CityPortrait` draws its procedural skyline and nothing is missing.
 *
 * ## Why it is not on the art manifest yet
 *
 * It should be, and it is the one thing here that is a stopgap rather than a rule: these are
 * paintings somebody has to make, which is exactly what the manifest exists to keep a list of.
 * Adding the five keys means five subjects in ART-PROMPTS, five rows regenerated into
 * ART-ORDER.md, a `type: 'city'` arm on `AssetRef` and the prompt-transcription test moved with
 * them, and that is a change to the art pipeline rather than to the world screen. Filed as the
 * follow-up it is.
 *
 * Note for whoever audits `assets/` next: like {@link buildingPortraitUrl}, this is a **bare
 * filename** lookup that never touches `ART_MANIFEST`, so a file it resolves looks orphaned to
 * anything that diffs the delivery directory against the manifest's keys. It is not.
 */
export function cityPortraitUrl(cityId: string): string | null {
  /*
   * A portrait of its own first, then the city's own map painting, then nothing.
   *
   * The second step is what puts a real picture on the world screen today. Ashfall and Terminus
   * each have a painted whole-city map on the manifest (`plate-city`, `plate-city-terminus`), and
   * a card drawing a procedural skyline beside a city that has a painting was the card telling a
   * player the place is not drawn yet when it is. The crop is severe, because a 21:10 map into a
   * tall card keeps about a fifth of its width, but a fifth of the real city reads as that city
   * and a generated silhouette reads as any city.
   *
   * A dedicated `city-<id>.webp` still wins, for the day somebody paints a portrait rather than a
   * map: a map is a plan and a portrait is a view, and the card wants the view.
   */
  const own = DELIVERED_ART.get(`city-${cityId}.webp`);
  if (own !== undefined) return own;
  return deliveredUrl({ type: 'plate', plate: cityPlateKey(cityId) });
}

/**
 * The manifest's plate key for a city's whole map.
 *
 * Ashfall's is the unsuffixed `plate-city`, because it was the only city when it was named and
 * renaming a delivered key would move a file, a prompt, a licensing row and three test pins to say
 * something that is already true.
 */
function cityPlateKey(cityId: string): string {
  return cityId === DEFAULT_CITY_ID ? 'city' : `city-${cityId}`;
}
