import { readFileSync } from 'node:fs';
import { describe, expect, it, vi } from 'vitest';
import {
  BLUEPRINT_PAGE_IDS,
  BLUEPRINTS,
  BUILDING_KINDS,
  CITY_DISTRICTS,
  MISSION_TEMPLATES,
  MODIFICATIONS,
  PERK_CATALOG,
  RESEARCH_ITEMS,
  TRAP_CATALOG,
  UNIT_CATALOG,
  VEHICLES,
} from '@frontline/shared';
import {
  anchor,
  clip,
  clock,
  DEFAULT_DOC_PATH,
  main,
  MAX_CELL,
  money,
  parseArgs,
  renderDoc,
  sections,
} from './catalog-doc.js';

const doc = renderDoc();

describe('the document', () => {
  it('opens with the title, the generated note and the board’s block about the removed tag', () => {
    const [title, note, heading, block] = doc.split('\n\n');
    expect(title).toBe('# Frontline content catalogue');
    expect(note).toContain('Generated by `pnpm catalog:doc`');
    expect(heading).toBe('## Removed: the "Ground pays" tag on the mission board');
    expect(block).toContain(
      'The mission board used to carry a tag at the right of the "Board 1 of N" row',
    );
    expect(block).toContain('9 percentage points per point of district difficulty above 1');
    expect(block).toContain('`PAY_PERCENT_PER_DIFFICULTY`');
    expect(block).toContain('`PAY_PERCENT_PER_LEVEL`');
    expect(block).toContain('(maintainer request, 2026-09-10)');
    expect(block).toContain('The per-card "expected haul" already shows the scaled figures.');
  });

  /**
   * The reason the doc is generated rather than written: a page added to a blueprint has to turn
   * up here without anybody remembering to add it.
   */
  it('names every blueprint page', () => {
    for (const id of BLUEPRINT_PAGE_IDS) expect(doc, id).toContain(`\`${id}\``);
    expect(BLUEPRINT_PAGE_IDS.length).toBeGreaterThan(0);
  });

  it('names every mission template', () => {
    for (const template of MISSION_TEMPLATES) {
      expect(doc, template.id).toContain(`\`${template.id}\``);
      expect(doc, template.name).toContain(template.name);
    }
    expect(MISSION_TEMPLATES.length).toBeGreaterThan(0);
  });

  it('names every entry of the other catalogues it claims to list', () => {
    const ids = [
      ...BLUEPRINTS.map((spec) => spec.id),
      ...TRAP_CATALOG.map((spec) => spec.id),
      ...UNIT_CATALOG.map((spec) => spec.id),
      ...VEHICLES.map((spec) => spec.id),
      ...BUILDING_KINDS,
      ...MODIFICATIONS.map((spec) => spec.id),
      ...RESEARCH_ITEMS.map((spec) => spec.id),
      ...PERK_CATALOG.map((perk) => perk.id),
      ...CITY_DISTRICTS.map((district) => district.id),
    ];
    for (const id of ids) expect(doc, id).toContain(`\`${id}\``);
  });

  it('says which file to edit under every heading, and links each from the contents', () => {
    for (const section of sections()) {
      expect(doc, section.title).toContain(`## ${section.title}`);
      expect(doc, section.title).toContain(`- [${section.title}](#${anchor(section.title)})`);
      for (const source of section.sources) {
        expect(doc, source).toContain(`\`${source}\``);
        expect(source.startsWith('packages/shared/src/'), source).toBe(true);
      }
    }
  });

  /**
   * A row per entry is the rule, and a description that runs on is what breaks a wide table.
   * Measured on the longest blurb in the roster rather than on a cell count: the doc has to hold
   * the cut version and not the full one.
   */
  it('cuts the longest authored blurb rather than printing it whole', () => {
    const longest = [...UNIT_CATALOG].sort((a, b) => b.blurb.length - a.blurb.length)[0];
    expect(longest).toBeDefined();
    expect(longest!.blurb.length).toBeGreaterThan(MAX_CELL);
    expect(doc).toContain(clip(longest!.blurb));
    expect(doc).not.toContain(longest!.blurb);
  });

  /** The one deliberately wide cell is the attribute group list; nothing else comes near it. */
  it('keeps every table cell readable', () => {
    const widest = doc
      .split('\n')
      .filter((line) => line.startsWith('|'))
      .flatMap((line) =>
        line
          .split('|')
          .slice(1, -1)
          .map((part) => part.trim()),
      )
      .reduce((max, part) => Math.max(max, part.length), 0);
    expect(widest).toBeLessThan(300);
  });

  it('has no stray pipe breaking a table row', () => {
    const rows = doc.split('\n').filter((line) => line.startsWith('| `'));
    expect(rows.length).toBeGreaterThan(500);
    for (const row of rows) expect(row.endsWith('|'), row).toBe(true);
  });
});

describe('formatting', () => {
  it('cuts a long line to the cap and marks it', () => {
    const long = 'x'.repeat(200);
    expect(clip(long)).toHaveLength(MAX_CELL);
    expect(clip(long).endsWith('…')).toBe(true);
    expect(clip('short')).toBe('short');
    expect(clip('a\n  b')).toBe('a b');
  });

  it('writes a bundle in the words the stockpile uses, in stockpile order', () => {
    expect(money({ scrap: 700, caps: 400, planks: 520 })).toBe('400 Caps, 700 Scrap, 520 Planks');
    expect(money({})).toBe('free');
  });

  it('reads a build clock the way the board does', () => {
    expect(clock(45)).toBe('45s');
    expect(clock(20 * 60)).toBe('20m');
    expect(clock(90 * 60)).toBe('1h 30m');
    expect(clock(2 * 3600)).toBe('2h');
  });

  it('slugs a heading the way GitHub does', () => {
    expect(anchor('Unit upgrades (refits)')).toBe('unit-upgrades-refits');
    expect(anchor('Environment labels and weather')).toBe('environment-labels-and-weather');
  });
});

describe('sections', () => {
  it('counts what it lists, and lists everything the catalogues hold', () => {
    const byTitle = new Map(sections().map((section) => [section.title, section]));
    expect(byTitle.get('Missions')?.rows).toBe(MISSION_TEMPLATES.length);
    expect(byTitle.get('Units')?.rows).toBe(UNIT_CATALOG.length);
    expect(byTitle.get('Research')?.rows).toBe(RESEARCH_ITEMS.length);
    expect(byTitle.get('Officer perks')?.rows).toBe(PERK_CATALOG.length);
    expect(byTitle.get('Building modifications')?.rows).toBe(MODIFICATIONS.length);
    expect(byTitle.size).toBe(sections().length);
  });
});

describe('parseArgs', () => {
  it('defaults to writing the committed document', () => {
    expect(parseArgs([])).toMatchObject({ check: false, docPath: DEFAULT_DOC_PATH });
  });

  it('reads --check and --out', () => {
    expect(parseArgs(['--check'])).toMatchObject({ check: true });
    expect(parseArgs(['--out', 'x.md']).docPath).toMatch(/x\.md$/);
  });

  it('rejects an unknown flag and a missing value', () => {
    expect(() => parseArgs(['--nope'])).toThrow(/Unknown argument/);
    expect(() => parseArgs(['--out'])).toThrow(/needs a value/);
  });
});

describe('--check', () => {
  /**
   * The gate that stops the sheet going stale: adding a unit changes `renderDoc`, and this fails
   * until somebody runs `pnpm catalog:doc` and commits the result.
   */
  it('matches the committed docs/CATALOG.md, character for character', async () => {
    expect(readFileSync(DEFAULT_DOC_PATH, 'utf8')).toBe(doc);
    expect(await main(['--check'])).toBe(0);
  });

  it('fails and says what to run when the document is missing', async () => {
    const err = vi.spyOn(process.stderr, 'write').mockReturnValue(true);
    expect(await main(['--check', '--out', 'docs/CATALOG-nope.md'])).toBe(1);
    expect(err.mock.calls.map((call) => String(call[0])).join('')).toContain('pnpm catalog:doc');
    err.mockRestore();
  });
});
